### ISSUE TITLE
many users in system

### ISSUE THREAD

**Issue by mohsen-unique** [alexbers/mtprotoproxy#104]
hi 
when you have many user the script go slowly.
for example i have 5000 user and for every user i have 1 secret the ping go very high (4000) and everything go slowly
i see the code in line 664 we have for loop for check secret. this loop Scrolling all secret key in config file for every connection. in this case we have 5000 secret this is why the script go slowly.
is there any way to fix this problem?

**Comment by alexbers** [comment]
hello, I am afraid the telegram protocol doesn't support users. Now the proxy tries to decrypt the first packet with various secrets until it succeed.

To fix the problem it is possible to run several proxy servers on different ports with smaller amount of users each.

**Comment by mohsen-unique** [comment]
can we have threading for that?
for example for each secret we have we check it in different thread and when one of the thread found that, message to all other thread to stop working.
i not know python but i thing this work for it

**Comment by alexbers** [comment]
the threading will not decrease the overall cpu time, the different ports approach with smaller number of users should do the better work
