### ISSUE TITLE
What is active fingerprinting

### ISSUE THREAD

**Issue by thisismzm** [alexbers/mtprotoproxy#108]
I have the following line in my error log:
`Active fingerprinting detected from xx.xx.xx.xx, dropping it`
What is the meaning of it? What I have to do?

**Comment by seriyps** [comment]
DPI can capture 1st 64 bytes of data from telegram client connecting to mtproto proxy and then DPI sends this packet to proxy again.
Proxy then replies with some fixed-size response, so, this way DPI could prove that this is telegram proxy and not some other type of server. And proxy will be blocked.
But, from my experience, it looks like this protection doesn't help =(

**Comment by thisismzm** [comment]
> DPI can capture 1st 64 bytes of data from telegram client connecting to mtproto proxy and then DPI sends this packet to proxy again.
> Proxy then replies with some fixed-size response, so, this way DPI could prove that this is telegram proxy and not some other type of server. And proxy will be blocked.
> But, from my experience, it looks like this protection doesn't help in Iran =(

You mean that this message is saying that DPI is trying to detect my proxy but I'll drop it and it (blocking) will not happen?

**Comment by seriyps** [comment]
well, this is the idea, yes.

**Comment by thisismzm** [comment]
> well, this is the idea, yes.

Are you saying that this won't work in Iran? Why?

**Comment by thisismzm** [comment]
> well, this is the idea, yes.

Can I change the following config?
`REPLAY_CHECK_LEN`
What numbers can I set to it?

**Comment by seriyps** [comment]
> Are you saying that this won't work in Iran?

At least all my proxies with this protection enabled (I use Erlang proxy) were blocked

> Why?

I don't know why, but proxies were blocked
