### ISSUE TITLE
updating config file without restarting 

### ISSUE THREAD

**Issue by pouryare** [alexbers/mtprotoproxy#109]
How can I add users or change config file without restarting the proxy?

**Comment by HirbodBehnam** [comment]
I really doubt because only once `USERS` is set and it's [here](https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L33).
Unless @alexbers adds a feature.

**Comment by alexbers** [comment]
Hello,

This functionality was just implemented: https://github.com/alexbers/mtprotoproxy/commit/a2890cf21320dbfef23a3620ffa6e11a44619895

To reload the config you can send the SIGUSR2 signal to the proxy proccess

**Comment by erfantkerfan** [comment]
How to send the SIGUSR2 signal to the proxy proccess in Ubuntu when using proxy in docker-compose?

**Comment by alexbers** [comment]
Just like without the docker-compose - find a process and send a signal to it.

**Comment by pouryare** [comment]
@alexbers 
Can you please add code to  `if hasattr(signal, 'SIGUSR2')` to print  `print_tg_info()` again?
when I add a user to config file I need their fake_tls secrets.

**Comment by alexbers** [comment]
Done, https://github.com/alexbers/mtprotoproxy/commit/80062c95bc488b4f5b5dc34833812769eaeee3a4
