### ISSUE TITLE
docker exec user process caused "permission denied"

### ISSUE THREAD

**Issue by ParaNULL** [alexbers/mtprotoproxy#112]
hi , just updated my dockerfile  and docker-compose and after Successfully creating the container i get this error on logs command and cant connect to proxy either ...
mtprotoproxy_1  | standard_init_linux.go:207: exec user process caused "permission denied"

**Comment by alexbers** [comment]
Hello, could you please retry with the latest master.

**Comment by ParaNULL** [comment]
Problem solved using that explicit launch... thanks
