### ISSUE TITLE
Test Fake TLS

### ISSUE THREAD

**Issue by HirbodBehnam** [alexbers/mtprotoproxy#113]
Hello
Is there anyway (right now) to test the fake TLS? or we should just wait more?

**Comment by HirbodBehnam** [comment]
OK just for you info, I installed telegram desktop v1.7.15 Beta on Ubuntu with snap. It works with it.
Just type in your terminal:
```
sudo snap install telegram-desktop --edge
```
And you will have the beta version of the app that works with the new method.
You need to get and compile the dev branch of [TG Desktop](https://github.com/telegramdesktop/tdesktop/tree/dev)

**Comment by pouryare** [comment]
@HirbodBehnam 
sorry to bother you. Do you know what exactly this Fake TLS is?

**Comment by seriyps** [comment]
@pouryare it's to make MTProto proxy traffic indistinguishable from normal TLS (https). It's not yet released with any Telegram client except desktop beta.

**Comment by HirbodBehnam** [comment]
BTW I'm so dumb. I just realized that I can do the same thing by going into options->Advanced->Install beta versions and the version that contains the fake TLS will be installed.

**Comment by pouryare** [comment]
Did you try it on windows?

**Comment by pouryare** [comment]
@HirbodBehnam 
Have you tried it in windows?

**Comment by HirbodBehnam** [comment]
Yes, I can confirm both @seriyps and @alexbers proxies are working on Windows!

**Comment by pouryare** [comment]
I have the latest beta version but when I click on these new fake_tls link it says 

> the proxy link is invalid

**Comment by HirbodBehnam** [comment]
I tried with `00000000000000000000000000000000` secret that resulted in `7gAAAAAAAAAAAAAAAAAAAABnb29nbGUuY29t`

**Comment by pouryare** [comment]
I sent you an Email

**Comment by pouryare** [comment]
This is my secret that telegram says is invalid 
`c6489cc998ebe1df17cadbb4525e4e9f`
`7nQqPS2jKjWCQ6F7Za%2B0ViJnb29nbGUuY29t`
and I tired another proxy from someone else it worked!
