### ISSUE TITLE
What does Fake TLS do?

### ISSUE THREAD

**Issue by erfantkerfan** [alexbers/mtprotoproxy#114]
I didn't exactly understood the functionality of fake TLS.
What does it do?

**Comment by alexbers** [comment]
It allows to make telegram protocol look like tls (https) to prevent the blocking the telegram. Now the telegram can be detected as an unknown protocol. In some countries to be an unknown protocol is enough for speed restriction or blocking. This new mode requires the support from the client side. For now, only the beta version of telegram supports these feature. The support for mobile clients will be likely be added in the future by the telegram authors

**Comment by erfantkerfan** [comment]
very nicely explained ...
thanks
