### ISSUE TITLE
Experimental link doesn't work in Telegram desktop beta 1.7.15

### ISSUE THREAD

**Issue by FreedomPrevails** [alexbers/mtprotoproxy#115]
I was trying to test the new experimental proxy method in Telegram desktop beta 1.7.15 but it says the proxy link -which is generated by mtprotoproxy- is invalid.
The normal link works fine.
Here are the links:
```
tg: tg://proxy?server=x.x.x.x&port=443&secret=ddc54a3eae90544e68a37cbe41c5d31442
tg: tg://proxy?server=x.x.x.x&port=443&secret=7sVKPq6QVE5oo3y%2BQcXTFEJnb29nbGUuY29t
```
I see other users have the same issue in other topic https://github.com/alexbers/mtprotoproxy/issues/113

**Comment by seriyps** [comment]
`%2B` is urlencoded `+`, but telegram only understands "urlsafe" version of base64: all `+` should be replaced with `-` and all `/` with `_`:

https://github.com/seriyps/mtproto_proxy/blob/c31ba04e5681a2991ce495a6c17e5fb94357daa7/src/mtp_fake_tls.erl#L78-L84

But it's better to be fixed in source code than manually later:

https://github.com/alexbers/mtprotoproxy/blob/80062c95bc488b4f5b5dc34833812769eaeee3a4/mtprotoproxy.py#L1423

`base64.b64encode(tls_secret)` should be replaced with `base64.urlsafe_b64encode(tls_secret))`

**Comment by FreedomPrevails** [comment]
@seriyps Thanks ! replacing %2B with `-` resolved the issue. @alexbers

**Comment by HirbodBehnam** [comment]
BTW guys they released the version of the MTProto proxy that supports the fake TLS!
On Android it's version 5.10
On PC it's version 1.8

**Comment by hookzof** [comment]
> BTW guys they released the version of the MTProto proxy that supports the fake TLS!
> On Android it's version 5.10
> On PC it's version 1.8

Confirm! Also works on latest iOS.

**Comment by pouryare** [comment]
Is this feature need any module?
I can't even connect to the default secret.

**Comment by FreedomPrevails** [comment]
If you are interested I have forked the repo and added TLS_ONLY option and fixed the TLS encoding bug :
https://github.com/FreedomPrevails/mtprotoproxy

**Comment by pouryare** [comment]
@FreedomPrevails 
I tried it but it doesn't work either.

**Comment by FreedomPrevails** [comment]
@pouryare May be your IP is blocked or something else, you cant even connect to default secret. Your issue has nothing to do with TLS.

**Comment by pouryare** [comment]
@FreedomPrevails 
I can connect to non TLS.

**Comment by FreedomPrevails** [comment]
@seriyps I found out something interesting, i fixed the function to `base64.urlsafe_b64encode` and it generates a secret which includes a `-` character. but ios version of telegram, doesnt accept the secret if it has the `-` char, I had to change it to `+` manually so it would accept the secret !
The android version accepts the secret with `-` char.

**Comment by alexbers** [comment]
it seems there is a bug in the ios client. Hope they will fix it

**Comment by FreedomPrevails** [comment]
Yes, I opened an issue an Telegram-iOS github:
https://github.com/TelegramMessenger/Telegram-iOS/issues/118

**Comment by medfan00** [comment]
After generating the secret and registering the bot in @MTProxybot it worked.

**Comment by FreedomPrevails** [comment]
This issue is resolved.
