### ISSUE TITLE
how to see the number of active connections count?

### ISSUE THREAD

**Issue by hamed-shirbandi** [alexbers/mtprotoproxy#12]
i need to monitor proxies and see the number of users of them. how can i do that?

**Comment by alexbers** [comment]
The proxy prints those stats every 10 minutes. They look like this

```
Stats for 05.06.2018 22:06:11
tg: 29 connects (0 current), 0.04 MB
tg2: 1268 connects (0 current), 0.02 MB
```
If you're using docker, the `docker-compose logs` command can be used to see the number of active connections

**Comment by Allineer** [comment]
@alexbers, how about more "parseable" statistics format?
For example, JSON or CSV or key=value via http(s) request or CLI command or rewriteable file like openvpn-status.log?

```
users=tg,tg2
tg.connects=29
tg.curr_connects=0
tg.octets=0.04
tg.msgs=111
tg2.connects=1268
tg2.curr_connects=0
tg2.octets=0.02
tg2.msgs=222
```


```
tg;29;0;0.04;111
tg2:1268;0;0.02;222
```

Thanks!

**Comment by seriyps** [comment]
@Allineer you can have statistics in Prometheus format if you check [prometheus branch](https://github.com/alexbers/mtprotoproxy/tree/prometheus)

**Comment by Allineer** [comment]
@seriyps Спасибо!

**Comment by ParaNULL** [comment]
docker-compose logs doesn't echo the same output as before! it doesn't show the connection stats and numbers!

**Comment by alexbers** [comment]
do you use prometheus branch? could you send the output of docker-compose logs command (please, replace your server ip with 0.0.0.0)?

**Comment by masoudelete** [comment]
@alexbers @seriyps Is there a way to see the number of connections with when I'm running the proxy with Python command? I ran 6 instances with `tmux` on a 6cpu server

**Comment by alexbers** [comment]
yes, you can use `netstat -tn` command, like `netstat -tn | wc -l`

**Comment by seriyps** [comment]
@alexbers it will show both connections from clients to proxy and from proxy to telegram servers. Also, it will show other connections on the system. So, it might be bit better to use `ss -nt state established '( sport = 443 )' |  wc -l` (here 443 is proxy port; if proxy uses different port, replace 443 with yours

**Comment by alexbers** [comment]
The Prometheus support have been merged to master
