### ISSUE TITLE
Should the socket have “ee” or “dd” at the beginning?

### ISSUE THREAD

**Issue by medfan00** [alexbers/mtprotoproxy#121]
Should the socket have “ee” or “dd” at the beginning?
As far as I know:
The first two letters - ee - Fake TLS + random message length (DPI cannot determine the protocol, the first message and all subsequent ones look like HTTPS / TLS)

**Comment by alexbers** [comment]
The secret format for Fake TLS is: ee + secret_as_hex(16 bytes) + domain_as_hex

**Comment by FreedomPrevails** [comment]
Just to add to alexbers message, after creating `ee + secret_as_hex(16 bytes) + domain_as_hex`, it is encoded in base64. so from user point of view, it doesnt start with `ee`. It is just a random string.

**Comment by medfan00** [comment]
> Just to add to alexbers message, after creating `ee + secret_as_hex(16 bytes) + domain_as_hex`, it is encoded in base64. so from user point of view, it doesnt start with `ee`. It is just a random string.

No. 

https://github.com/alexbers/mtprotoproxy/issues/118#issuecomment-520806609

**Comment by medfan00** [comment]
The issue is resolved. "ee" at the beginning may point to Fake TLS with a secret length of more than 32 bytes.
