### ISSUE TITLE
get client ips

### ISSUE THREAD

**Issue by mohamad77** [alexbers/mtprotoproxy#128]
Hello
How can i get or view client IPs that connected to service?
This [pull](https://github.com/alexbers/mtprotoproxy/pull/47) work but its old and does n't support fake tls and new updates
thanks for your best app

**Comment by alexbers** [comment]
netstat -an

**Comment by mohamad77** [comment]
i use port forwarding and i need to get client ips per secret
is that possible?
thanks

**Comment by ea1234567** [comment]
> netstat -an

How can do this on windows?

**Comment by alexbers** [comment]
ea1234567: in windows the command should be the same

**Comment by alexbers** [comment]
mohamad77: this is not possible, but you can try to add `print(user, cl_ip)` after `cl_ip, cl_port = peer` if you need

**Comment by HirbodBehnam** [comment]
Hello
Actually where is another good way to format the output of netstat
```
netstat -atn | tr -s ' '| cut -f4 -d ' ' | grep 443
```
where 443 is your proxy port.
Also to count the connections use `netstat -atn | tr -s ' '| cut -f4 -d ' ' | grep 443 | wc -l`

**Comment by alexbers** [comment]
I've also added the printing of all new ip addresses who connects to the proxy
