### ISSUE TITLE
new config option

### ISSUE THREAD

**Issue by shraik** [alexbers/mtprotoproxy#129]
is it possible to add these variables to the config file config.py ?
Возможно добавить определение этих переменных в конфиг-файле config.py ?

    # the next host's port to forward bad clients
    conf_dict.setdefault("MASK_PORT", 443)

**Comment by alexbers** [comment]
Да, если написать MASK_PORT в config.py, то он применится

**Comment by alexbers** [comment]
Yes, if you add the MASK_PORT in the config.py, it will be applied
