### ISSUE TITLE
uvloop

### ISSUE THREAD

**Issue by valsha** [alexbers/mtprotoproxy#134]
Hi, how to run mtprotoproxy with uvloop? 
-with uvloop module to get an extra speed boost
Do i need install only "pip install uvloop" and run as always:
"python3 mtprotoproxy.py"
Thanks.

**Comment by alexbers** [comment]
Yes, you are right. The proxy will use uvloop if it is available.

**Comment by iShift** [comment]
Why not to use this by default ?

**Comment by alexbers** [comment]
Because the CPU consumption is usually not a problem. Before you have CPU problems, you will likely have bandwidth problems, because many hosting providers restrict your traffic to several terabytes per month which will be consumed in several days even on cheapest hosts with one CPU core.

**Comment by erfantkerfan** [comment]
how I cam check if Im using uvloop?

**Comment by alexbers** [comment]
I've just committed a message if you are using it: https://github.com/alexbers/mtprotoproxy/commit/50cd74051fbb426a05d9c97f624b45cf60517f5a. You can add the same to your version or update the proxy

**Comment by erfantkerfan** [comment]
thanks I was using the last stable branch
