### ISSUE TITLE
What domain I should use for TLS

### ISSUE THREAD

**Issue by skipik** [alexbers/mtprotoproxy#136]
Я вижу, что стандартное google.com использовать не рекомендуется. Если я впишу туда, например, github.com - это нормально? Или нужно использовать что-то другое?

**Comment by alexbers** [comment]
Нормально вписать любой сайт, но желательно, чтобы TLS 1.3 поддеривал. Это нужно чтобы если придёт сканер и будет слать хитрые запросы, затрагивающие реализацию TLS, чтобы на эти запросы отвечал какой-то реальный сервер. Другие версии TLS тоже можно, но это более заметно.

Ещё можно TLS_DOMAIN указать например github.com, а MASK_HOST например e1.ru. Тогда активный сканер увидит просто сайт с невалидным сертификатом.

**Comment by skipik** [comment]
Спасибо за подробное объяснение!
