### ISSUE TITLE
Installation process in windows

### ISSUE THREAD

**Issue by rezavn** [alexbers/mtprotoproxy#14]
Hi dear @alexbers .
As you mentioned in this issue:
https://github.com/TelegramMessenger/MTProxy/issues/31
I wonder if you can help me with installation process.
I know how to install python in Windows.
But i Do not know how to install this source code on windows.
Please give me the commands that i can install&launch mtprotoproxy in Python(windows).
I’ll do my best to publish your REP and make it to the most known mtproxy source code.
Regards,
Reza

**Comment by rezavn** [comment]
P.S:
Im kind of beginner so accept my apologies.

**Comment by alexbers** [comment]
Hi,

To copy the source, please, download it as zip with this folder:
![image](https://user-images.githubusercontent.com/742987/41031794-0ece3022-699b-11e8-94f1-5e80d354a621.png)

Then unpack it and launch with command: python mtprotoproxy.py (or python3 mtprotoproxy.py).

**Comment by rezavn** [comment]
Well thanks alot.
Unfortunately another issue has Came out of the blue.
Same as this issue:
https://github.com/alexbers/mtprotoproxy/issues/10
But i couldn’t figure how to solve it.
Please help me in this case. Proxy is working very well but when i set the AD_TAG it drops the connection. On the other hand i get exact ip address which my server has from the Python black box.
tg://proxy?server=<IP_ADDR>&port=3259&secret=0123456789abcdef0123456789abcdef
Also i checked with my other server and i keep receiving same issue.

**Comment by alexbers** [comment]
It looks like the proxy failed to determine your ip address and fallback to the scheme without ads.

Please, make sure that address https://v4.ifconfig.co/ip is available from your server.

**Comment by rezavn** [comment]
It can determine the ip.
yon.ir/ipsc

**Comment by alexbers** [comment]
May be when Windows asked you about allow or deny connections made by proxy, you pressed "deny"?

Also, please, try to change the string `ip_addrs = ["YOUR_IP"]` to `ip_addrs = ["104.167.14.113"]` in the mtprotoproxy.py file and rerun the program

**Comment by rezavn** [comment]
[error.txt](https://github.com/alexbers/mtprotoproxy/files/2076573/error.txt)

**Comment by rezavn** [comment]
By the way i can give you access to my own server so you can solve my issue or otherwise debug it.
Your free to do anything with it.

**Comment by rezavn** [comment]
Hi dear @alexbers.
Is there anyway that i can handle this issue?
Please help.

**Comment by alexbers** [comment]
https://github.com/alexbers/mtprotoproxy/commit/63b77ea637cdecf7448afdb1a477b5098cef5371 - I commited the patch against those errors, but these errors occur if the connection to telegram servers was failed. If you want me to check the server, you can send an access data to me (@bay3255 in telegram).

**Comment by alexbers** [comment]
The connection problems was because the host was having a wrong time. The telegram servers compare current time with the time reported by client and if they are different, the connection is dropped. It was a big surprise for me.

**Comment by rezavn** [comment]
Well i need to thank you for this big help.
Problem solved and the issue closed.
Regards,
Reza

**Comment by ea1234567** [comment]
i have this problem too 
my server time is same as my clients time
and https://v4.ifconfig.co/ip show my ip correctly
can i have your telegram id?
