### ISSUE TITLE
random TLS_DOMAIN

### ISSUE THREAD

**Issue by f242** [alexbers/mtprotoproxy#140]
Может имеет смысл добавить разнообразия хостов? В конфиге указать сразу пучок ну и чтобы они чередовались.

**Comment by alexbers** [comment]
на самом деле хост используется клиентом, а серверу нужен чтобы напечатать свой адрес в начале. Т.е. можно просто много ссылок сгененрировать. Хотя если один ip будет, например, и гуглом и яндексом, то это крайне подозрительно :)

**Comment by f242** [comment]
Точно, не подумал)
