### ISSUE TITLE
format of secret

### ISSUE THREAD

**Issue by mohsen-unique** [alexbers/mtprotoproxy#145]
hi
what is the format of secret? i mean in previous version the secret has this format dd+secret in config file but in this version i can't recognize the format.
how can found the original secret that can connect with it before run the program?
i want load secret from my database for that i want know the format

**Comment by seriyps** [comment]
If you are talking about `ee` secrets, the format is `ee + <original secret> + <hex-encoded fake-tls domain name>`.
You can construct ee secret with following python code:

```
import binascii

original_secret = b"57d843d08a62464d3ce484c573326241"
domain = b"google.com"

print(b"ee" + original_secret + binascii.b2a_hex(domain))
```

Also, see this webpage http://seriyps.ru/mtpgen.html
