### ISSUE TITLE
socket.send() raised exception.

### ISSUE THREAD

**Issue by SmOkEnksp** [alexbers/mtprotoproxy#149]
Доброго времени суток.
Не пойму в чем дело.
Вчера установил прокси, но коннект не стабильный и ничего не грузит.
конфиг:
PORT = 443
USERS = {
    "tg":  "xxx",
}
SECURE_ONLY = True
TLS_ONLY = True
TLS_DOMAIN = "www.yandex.ru"
AD_TAG = "xxx"

**Comment by karimi12** [comment]
use sudo (root) user for port 443
sudo python3 mtprotoproxt.py

and install cryptography:

apt install git curl build-essential libssl-dev zlib1g-dev
pip install cryptography
