### ISSUE TITLE
When multiple people connect, the proxy will be disconnected

### ISSUE THREAD

**Issue by hamed-shirbandi** [alexbers/mtprotoproxy#15]
When more than a few people are connected, the proxy is interrupted by the following error :

> Traceback (most recent call last):
>   File "mtprotoproxy.py", line 769, in <module>
>     main()
>   File "mtprotoproxy.py", line 750, in main
>     loop.run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 523, in run_forever
>     self._run_once()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1713, in _run_once
>     event_list = self._selector.select(timeout)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
>     r, w, _ = self._select(self._readers, self._writers, [], timeout)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
>     r, w, x = select.select(r, w, w, timeout)
> ValueError: too many file descriptors in select()

**Comment by alexbers** [comment]
Could you retry with the latest version of the proxy. This should be fixed by https://github.com/alexbers/mtprotoproxy/commit/b1431b6fa7b00957c4a1cc00cbc1f33787cfb14d

**Comment by p1ratrulezzz** [comment]
Running the latest version. Crypto package is installed, a lot of cpu is utilized and memory too. Got about 600 users per hour

**Comment by alexbers** [comment]
p1ratrulezzz: does it started to happen from some version? Could you send the program logs by telegram (@bay3255) or email (bay@hackerdom.ru). How much cpu and memory consumed?

For now, I set up a server to test the performance and trying to advertise it to get performance data on real users. For now I managed to get 80 permanent users (in peak time - about 500). For 80 users it consumes <1% of CPU.

**Comment by p1ratrulezzz** [comment]
Latest version 9f11d6d387. Just checked logs and saw a lot of errors like "Too many open files". I've increased max file limit to 500000 open files (ulimit -n + sysctl fs.file-max) 

Stats for now

```
Stats for 10.06.2018 23:01:50
tg: 0 connects (0 current), 0.00 MB
tg2: 6918 connects (280 current), 584.32 MB
tg3: 0 connects (0 current), 0.00 MB
tg4: 0 connects (0 current), 0.00 MB
tg5: 0 connects (0 current), 0.00 MB

```

**Comment by alexbers** [comment]
I also often forgot to increase this limit while debugging. In the next version I'll try to do something with it. I think about setting a file limit in the beginning of the program, getting it afterwards and warn user if it is too low.

Also, the using of pypy3 implementation of python + pycryptodome should give an improvement in performance.

**Comment by alexbers** [comment]
I did some benchmarking to show what can you expect from the proxy. I used the cheapest VM instance (5$/month) in Digital Ocean for testing. All numbers are **per second**. 

MSG SIZE (AVG) |   Python 3.5                 |      Python 3.5 + uvloop        |            PYPY3
---------------|------------------------------|---------------------------------|-----------------------------------
200KB          |  150 msg (30MBytes)          |    163 msg (33MBytes)           |         160 msg (33MBytes)
100KB          |  315 msg (32MBytes)          |    294 msg (30MBytes)           |         312 msg (32MBytes)
 50KB          |  555 msg (28MBytes)          |    579 msg (30MBytes)           |         565 msg (29MBytes)
 25KB          | 1000 msg (25MBytes)          |    1049 msg (25MBytes)          |         1074 msg (26MBytes)
 12KB          | 1640 msg (20MBytes)          |    1655 msg (20MBytes)          |         1866 msg (23MBytes)
  6KB          | 2320 msg (14MBytes)          |    2735 msg (17MBytes)          |         3143 msg (19MBytes)
  2KB          | 3356 msg (6.9MBytes)         |    4112 msg (8.5MBytes)         |         5401 msg (11MBytes)
  1KB          | 3595 msg (3.7MBytes)         |    4648 msg (4.7MBytes)         |         6439 msg (6.7MBytes)
 512B          | 4169 msg (2.1MBytes)         |    5100 msg (2.6MBytes)         |         7852 msg (4.0MBytes)
 256B          | 4290 msg (1.1MBytes)         |    5704 msg (1.5MBytes)         |         8391 msg (2.1MBytes)
  16B          | 4457 msg (<0.1MByts)         |    5748 msg (0.1MBytes)         |         8604 msg (0.1MBytes)

**Comment by p1ratrulezzz** [comment]
yes, pypy3 shows best values (binary rocks!) But I didn't managed how to install pycrypto package within pypy3. Though with uvloop+python3+pycryptodome it looks ok for now

**Comment by alexbers** [comment]
I used these commands for the testing:
```
wget 'https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2'
tar xf pypy3-v6.0.0-linux64.tar.bz2
pypy3-v6.0.0-linux64/bin/pypy3 -m ensurepip
pypy3-v6.0.0-linux64/bin/pip3 install pycryptodome
pypy3-v6.0.0-linux64/bin/pypy3 mtprotoproxy.py
```

**Comment by alexbers** [comment]
I added auto-increasing the open file limit, on the maximum value that is available for user: https://github.com/alexbers/mtprotoproxy/commit/8177f2b12ddf1d554c0c28a62188899e05b0882d
