### ISSUE TITLE
what is unit USER_DATA_QUOTA ?

### ISSUE THREAD

**Issue by karimi12** [alexbers/mtprotoproxy#150]
what is unit USER_DATA_QUOTA ?

what is mean this code?
```
    USER_DATA_QUOTA ={
     "tg1":100
   }
```

**Comment by alexbers** [comment]
bytes

**Comment by erfantkerfan** [comment]
User data limit in bytes unit
tg1 means the user with name of tg1 has 100 bytes of data cunsumption limit

**Comment by ALEXSANPEDRO** [comment]
Where i can find this in code? i have lot of channels(more than 500) and it takes a long time to load. Maybe it a good choise to increase 100 to 1000?
