### ISSUE TITLE
android can't connect to fake tls proxy

### ISSUE THREAD

**Issue by iShift** [alexbers/mtprotoproxy#153]
Hi, i have some strange problem - on IOS/MAC proxy works perfectly but on Android - they can't connect, android devices have last telegram version from GPlay, i tested it with 3 different phones....

**Comment by alexbers** [comment]
Hi, does it work with ad tag disabled?

**Comment by iShift** [comment]
@alexbers 
found problem (not in proxy), when you copy link from android and tg desktop vs iOS client - you have different link. 

From desktop and android it start with ee
From ios it start from another data (but in UI you see ee)

iOS client works with all link (for iOS and for Android) but desktop and android only works with true ee secret...

**Comment by iShift** [comment]
interesting, that in you proxy link example in https://habr.com/ru/post/461171/ you post incorrect link (looks that from iOS client) - this is same bug, links with 7 only iOS can add

>tg://proxy?server=178.62.232.110&port=3256&secret=7gAAAAAAAAAAAAAAAAAAAABnb29nbGUuY29t
