### ISSUE TITLE
IPv6 problem?

### ISSUE THREAD

**Issue by ed96win** [alexbers/mtprotoproxy#155]
Hey there. thanks for the great work.

I have a small droplet with your script installed on it and it works perfectly on IPV4 but the minute I enable IPV6 (by default) the proxy starts getting randomly disconnected/connected and no media (voice, pics, etc) can be downloaded.

1. the IPV6 itself is working. cuz it's being used in other programs without problem.
2. I've opened outgoing 8888 TCP port in firewall.

**Comment by Kirya2k** [comment]
Middle proxies also working on port 80. And mtprotoproxy update list proxies on 443 port.
You must opening also 80 и 443 TCP outgoing ports.

**Comment by ed96win** [comment]
@Kirya2k They're open by default. it's not a port problem. it "connects" but its extremely slow.

**Comment by Kirya2k** [comment]
Do you have normal ping and traceroute to ipv6 middle proxies of Telegram network ?
