### ISSUE TITLE
Socket leak

### ISSUE THREAD

**Issue by seriyps** [alexbers/mtprotoproxy#16]
On the latest master 07780602d1cd71b628519a7f746a2c55165fe9bd with AD_TAG enabled still get those kind of errors:

```
Fatal write error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0a312a9fd0>
transport: <_SelectorSocketTransport closing fd=801 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _write_ready
    n = self._sock.send(self._buffer)
TimeoutError: [Errno 110] Connection timed out

<..>

Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0a2daa5940>
transport: <_SelectorSocketTransport fd=792 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0a2d815ef0>
transport: <_SelectorSocketTransport fd=1557 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out

<..>

Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0a30fa0c18>
transport: <_SelectorSocketTransport fd=3524 read=polling write=<polling, bufsize=10611>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Stats for 07.06.2018 11:14:48
tg: 357181 connects (974 current), 8927.98 MB

Stats for 07.06.2018 11:15:18
tg: 357339 connects (985 current), 8945.99 MB

Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7f0a30c5ff28>
transport: <_SelectorSocketTransport fd=1520 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
```

So, both `send` and `recv` despite the fix from https://github.com/alexbers/mtprotoproxy/commit/07780602d1cd71b628519a7f746a2c55165fe9bd#diff-e2b821dc5d96409f0102669d33aa8637R671

Unfortunately stacktrace doesn't say much on asyncio, so, my guess is that it fails somewhere during handshake.

And it looks like it causes socket leaks:

![screenshot from 2018-06-07 13-19-26](https://user-images.githubusercontent.com/422014/41096606-75d4ec74-6a55-11e8-8461-4a43555792eb.png)

This peak to 40k was before latest patch (definitely leak) and what I have now is better, but it still grows.

**Comment by alexbers** [comment]
Thank you for report. I'll try to investigate an issue

**Comment by alexbers** [comment]
I added some logic to close connections more reliably (without trying to send buffered data). Please, retry with https://github.com/alexbers/mtprotoproxy/commit/63b77ea637cdecf7448afdb1a477b5098cef5371

**Comment by seriyps** [comment]
Yep, now I see some `Timeout, killing transport` and no stacktraces.
Let's see how it will behave in a long term then

**Comment by alexbers** [comment]
Also I made some corrections which should fix the client reconnections: https://github.com/alexbers/mtprotoproxy/commit/75927b49f5eff1cccc5c5844f6de4b5d21df1680

**Comment by seriyps** [comment]
@alexbers I switched to my own implementation today, but until then it looked stable, so, could be closed. Thanks!

**Comment by alexbers** [comment]
It is nice to hear that that is stable. I created some servers in the Internet and advertised it for wide public. Now I am monitoring them for socket leaks. 

Thank you for using, the bug is closed.
