### ISSUE TITLE
How to Add a WhiteList IP for Disable of  Reply-Attackers Feature

### ISSUE THREAD

**Issue by mostafamoeini** [alexbers/mtprotoproxy#166]
Because I Use NginX as a Reverse Proxy for MTProxy , I Need to Disable replay-attackers Feature Or atleast I Can add a White IP for Disable Prevent On That IP<br/>
How Can I do This?

**Comment by alexbers** [comment]
yes, you can put these two strings in the config.py:
```
BLOCK_IF_FIRST_PKT_BAD = False
REPLAY_CHECK_LEN = 0
```

**Comment by mostafamoeini** [comment]
> yes, you can put these two strings in the config.py:
> 
> ```
> BLOCK_IF_FIRST_PKT_BAD = False
> REPLAY_CHECK_LEN = 0
> ```

Thanks, It Works
