### ISSUE TITLE
wrong statistics

### ISSUE THREAD

**Issue by SinaXhpm** [alexbers/mtprotoproxy#170]
it has a wrong stats loger
one of logs when only i was connected to proxy

> tg: 97 connects (4 current), 2.92 MB, 1214 msgs

i havent even 100 msg overall

**Comment by alexbers** [comment]
The telegram client sends invisible messages. For example when you start typing the telegram client sends a message about it and other side can see "typing..". Or when somebody entered the chat you've got a message. The files are also transferred as  message sequence
