### ISSUE TITLE
Cant connect to proxy with android client

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#171]
My proxy was ok but today i cant connect with android client

Telegram desktop is ok

@alexbers

**Comment by alexbers** [comment]
Could you please provide more information to reproduce the bug.

1. Does the proxy works with all android clients or with specific one?
2. Does the proxy work on other servers?
3. Does the proxy work on this server with a default config?

Also please see similar issues: https://github.com/alexbers/mtprotoproxy/issues/153 https://github.com/alexbers/mtprotoproxy/issues/117

**Comment by ea1234567** [comment]
> Could you please provide more information to reproduce the bug.
> 
> 1. Does the proxy works with all android clients or with specific one?
> 2. Does the proxy work on other servers?
> 3. Does the proxy work on this server with a default config?
> 
> Also please see similar issues: #153 #117

I think this is telegram beta bug
Telegram stable and Telegram X is ok
