### ISSUE TITLE
Socket.send ?

### ISSUE THREAD

**Issue by F0restonn** [alexbers/mtprotoproxy#173]
What does it mean ? 
![image](https://user-images.githubusercontent.com/52072018/70388012-100b9600-19f8-11ea-8ddc-c4b7f54a5e94.png)

**Comment by F0restonn** [comment]
Proxy work normal, but I get those messages in logs

**Comment by alexbers** [comment]
This means there was some error while sending. Probably it is because some clients have unstable internet connection like grps
