### ISSUE TITLE
Fix OSError Too Many Open Files For Limited Servers

### ISSUE THREAD

**Issue by RaminSubZero** [alexbers/mtprotoproxy#174]
To Fix This Issue

Open file: /etc/security/limits.conf

Paste following towards end:
`*         hard    nofile      500000`
`*         soft    nofile      500000`
`root      hard    nofile      500000`
`root      soft    nofile      500000`
500000 is fair number. I am not sure what is max limit but 999999 (Six-9) worked for me once as far as I remember.

Open /etc/sysctl.conf 

Add following:

`fs.file-max = 2097152`

Run:

`sysctl -p`

**Comment by LeMaX10** [comment]
In docker fix.

Dockerfile:
after line:
```
COPY mtprotoproxy.py config.py /home/tgproxy/
```

add lines:
```
RUN echo "* hard nofile 500000\n* soft nofile 500000\nroot hard nofile 500000\nroot soft nofile 500000" > /etc/security/limits.conf
RUN echo "fs.file-max = 2097152" >> /etc/sysctl.conf
```

docker-compose down && docker-compose up -d
