### ISSUE TITLE
How to Enable Access Only With Private-Address

### ISSUE THREAD

**Issue by mostafamoeini** [alexbers/mtprotoproxy#181]
I need to Access to Proxy Server Just with Private-Address.<br/>

> for example : test1.alexbers.com and test2.alexbers.com are pointed to The Server , But I need to Access Proxy Server Just With test1.alexbers.com.<br/>

I Use NginX as Reverse Proxy

**Comment by alexbers** [comment]
The proxy server doesn't know which name was used to access the proxy. The client resolves the name first and then connects to the proxy.

But you can modify dns settings pointing test2.alexbers.com somewhere else.

**Comment by mostafamoeini** [comment]
Thanks
