### ISSUE TITLE
Best Way to Check Quality of Proxy Server

### ISSUE THREAD

**Issue by mostafamoeini** [alexbers/mtprotoproxy#182]
I am testing some senarios for Proxy Server (MTProto Based) such as :<br/>
- Direct MTProtoProxy without reverse
- MTProtoProxy with NginX reverse
- MTProtoProxy Running on multiple locations
- Even MTProtoProxy with Custom Config
- ...
**I need to know witch one has better quality (speed,ping,...).
At least Let Me know any tool to check that.**

**Comment by alexbers** [comment]
The best tool is the telegram client. It prints a ping time

**Comment by mostafamoeini** [comment]
Is there any other tool?

**Comment by alexbers** [comment]
I don't know other tools. But you can set up the proxy in the different setups and monitor the metrics

**Comment by mostafamoeini** [comment]
thanks
