### ISSUE TITLE
 Clients with error on the first packet after Telegram Android update

### ISSUE THREAD

**Issue by yarik2720** [alexbers/mtprotoproxy#183]
After Telegram Android client update there is issue, that some preview on android client are not loaded, sometimes it can't automatically connect to proxy until you open proxy settings.
In mtproto logs there is:
```
mtprotoproxy_1  | Clients with error on the first packet (possible replay-attackers):
mtprotoproxy_1  | 95.29.my.ip, 83 times
```

**Comment by DrKLO** [comment]
@alexbers what proxy is checking in this line https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L1625 ?
Android client is using PFS and can receive -404 (https://core.telegram.org/api/pfs) error from server when temp auth key is no longer valid, so after that client is generating new temp auth key.

When someone opens proxy settings and has other proxy addresses in here, client will receive -404 error via them and will regenerate temp auth key, so connection via your proxy will work again.

**Comment by thisismzm** [comment]
@alexbers After new update for Android client (5.13), I have this problem too.
What is the solution?

**Comment by alexbers** [comment]
The check is a protection against the replay attacks. It seems the new android client stopped to generate new connection parameters on the disconnect. For now you can put BLOCK_IF_FIRST_PKT_BAD=False in the config or enable the tls only mode. I’ll try to find more appropriate solution

**Comment by alexbers** [comment]
@DrKLO I've removed this hackish logic from the source: https://github.com/alexbers/mtprotoproxy/commit/66ac871a7454d27574a64a1a2d573acd1ee92b08

The overall idea was to additionally protect from proxy detectors by not forwarding error -404 to clients. The replay attacker can record the handshake and try to replay it as is and with bytes on some offset modified to random ones to cause an error. Then the attacker can look on answer lengths and detect the proxy.

Additionally the proxy remembers N last handshakes and doesn't allow to reuse them. But the detector can retry the attack later, for example, on the next day where the handshake is no in the list of last handshakes.

In TLS-mode the client sends its timestamp xored with hmac, which can be obtained by proxy. This allows the proxy to block old handshakes, but it doesn't give the full protection. The attacker can take the hmac from the wire, xor it with a timestamp when the packet is received and on the next day replay the packet xoring it again with the current timestamp, making the proxy to accept the packet.

To protect from this attack the 32-byte long hmac (proving that the client knows the secret) could be split on two 16-byte hmacs: the first one to prove the client knows the secret (xored with time); and the second one to prove the time is not modified. Or similar scheme. But this requires the client modification.

**Comment by yarik2720** [comment]
New Telegram for Android update and again issues with connecting to proxy.
```
mtprotoproxy_1  | Clients with time skew (possible replay-attackers):
mtprotoproxy_1  | 81.222.my.ip, clocks were 18 minutes behind
mtprotoproxy_1  | 85.173.xxx.xxx, clocks were 21 minutes behind
```

**Comment by Saebnejad** [comment]
ive got the same issue again after updating telegram

**Comment by alexbers** [comment]
Thanks, I am trying to debug this.

It looks the Android clients sends the old time. The proxy uses it to protect from replay-attackers, if the time is too old the client is blocked. I am thinking about making this feature disableable

**Comment by skipik** [comment]
Same here guys. I can't connect after the 5.15.0 update.

**Comment by yarik2720** [comment]
I also sent telegram client logs to telegram support.

**Comment by alexbers** [comment]
I added an option to ignore time skew: https://github.com/alexbers/mtprotoproxy/commit/1a63fdae1136bc8082b7aadb7f5d56f1b25d02fc. This should help Android clients until the problem is fixed

To use this option it is necessary to use the latest master branch (not stable branch) and add this line to config.py:
`
IGNORE_TIME_SKEW = True
`

**Comment by skipik** [comment]
Thanks, it works now! :-)

**Comment by NotSBad** [comment]
> 
> 
> I added an option to ignore time skew: [1a63fda](https://github.com/alexbers/mtprotoproxy/commit/1a63fdae1136bc8082b7aadb7f5d56f1b25d02fc). This should help Android clients until the problem is fixed
> 
> To use this option it is necessary to use the latest master branch (not stable branch) and add this line to config.py:
> `IGNORE_TIME_SKEW = True`

Thanks. While working? But is it not dangerous for protection?

**Comment by alexbers** [comment]
> Thanks. While it works, and not dangerous for protection?

It is dangerous. I hope the developers of android version fix it soon, so the protection could be enabled again.

**Comment by alexbers** [comment]
It seems they fixed the client: https://github.com/DrKLO/Telegram/commit/df90eface5ebd755ea86c3a4eec66fe5b6e29041
