### ISSUE TITLE
DeprecationWarning on Ctrl+C

### ISSUE THREAD

**Issue by pasha-zzz** [alexbers/mtprotoproxy#188]
/mtprotoproxy.py:2263: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead for task in asyncio.Task.all_tasks():

Python 3.8.1

**Comment by alexbers** [comment]
should be fixed by https://github.com/alexbers/mtprotoproxy/commit/f5ee5db86faeb9fdf6545bcad5d7ebf2fc345680
