### ISSUE TITLE
multiple mtproto servers

### ISSUE THREAD

**Issue by aminvakil** [alexbers/mtprotoproxy#19]
How can I run multiple mtproto servers simultaneously on different ports and different secrets and different channel_tags with multiple configs?

When I build the second one with docker-compose it erases the first one.

**Comment by HirbodBehnam** [comment]
I think you have to use Python to lunch your app. Just copy the project somewhere else and run that with Python3. I would also recommend you to use tmux to manage your proxies.

**Comment by aminvakil** [comment]
@alexbers thanks i would love to try it but unfortunately just last night my country blocked my IP after just two days of mtproto running on my server:-)
Now I can't risk my other IPs.
