### ISSUE TITLE
octetcs... what is?

### ISSUE THREAD

**Issue by Allineer** [alexbers/mtprotoproxy#192]
Hello! I have a simple question, but I don't understand:

`octets` in metrics meaning is equals to bytes?

If true - why then `octets` are called that?
If false - what is that?

Thanks)

**Comment by seriyps** [comment]
Octet is Byte. Named like that because Byte is 8 bits.
Why not name it just Bytes - I don't know.

ср, 12 февр. 2020 г., 13:58 Allineer <notifications@github.com>:

**Comment by alexbers** [comment]
The byte is not always 8 bit. From https://en.wikipedia.org/wiki/Byte:

> The byte is a unit of digital information that **most commonly** consists of eight bits. Historically, the byte was the number of bits used to encode a single character of text in a computer[1][2] and for this reason it is the smallest addressable unit of memory in many computer architectures.

> The size of the byte has historically been hardware dependent and no definitive standards existed that mandated the size. **Sizes from 1 to 48 bits have been used.**

> The term **octet** is used to unambiguously specify a size of eight bits. It is used extensively in protocol definitions.

**Comment by Allineer** [comment]
Thank you, guys.
