### ISSUE TITLE
Wrong HELP text for mtprotoproxy_user_msgs_to counter

### ISSUE THREAD

**Issue by Arderos** [alexbers/mtprotoproxy#193]
HELP text states "mtprotoproxy_user_msgs_to msgs proxied from user" for "mtprotoproxy_user_msgs_to" counter while it should be "mtprotoproxy_user_msgs_to msgs proxied to user"

**Comment by alexbers** [comment]
fixed in https://github.com/alexbers/mtprotoproxy/commit/a95b1ec3c143d9783fbe393b635b5339474d8d52, thanks
