### ISSUE TITLE
Clients with time skew (possible replay-attackers)

### ISSUE THREAD

**Issue by NotSBad** [alexbers/mtprotoproxy#194]
Please help solve the problem:
```
Clients with time skew (possible replay-attackers):
127.0.0.1, clocks were 43 minutes behind
```

The latest version of Telegram.  Thanks.

What is most interesting is that only Android leaves for the block, and another moment, under the same ip which was banned for example using Android, another device (the client is not Android) works fine under the same ip.

**Comment by NotSBad** [comment]
UPD: did so https://github.com/alexbers/mtprotoproxy/commit/1a63fdae1136bc8082b7aadb7f5d56f1b25d02fc while it works

**Comment by NotSBad** [comment]
But there are still warnings in the server logs, but it doesn’t ban, should it be so? Or is it still banned?

**Comment by Vanav** [comment]
I confirm this issue: connection errors with latest Android official client, same message in logs.

**Comment by alexbers** [comment]
It seems the developers of android version introduced some bug with timestamps: https://github.com/DrKLO/Telegram/commit/2eafc07314532d9ec31bdb63378a30a4969c26db (the changes are at the top)
