### ISSUE TITLE
ERR_CONNECTION_CLOSED for proxied domain after 22.02.2020 commit

### ISSUE THREAD

**Issue by evg-berg** [alexbers/mtprotoproxy#199]
Hi there!

There is issue with accessing to proxied domain via browser after 22.02.2020 commit - I receiving ERR_CONNECTION_CLOSED.
Reverting to 17.02.2020 version fixing issue.

My network config: sslh:443 -> mtprotoproxy:8443 -> apache:6443 (with custom domain name and cert from Let's Encrypt).
I also tryed www.google.com as proxied domain - same issue.

My config.py:
PORT = 8443
USERS = {
    "tg": "<custom_secret>"
}
AD_TAG = "<custom_tag>"
MODES = {
    "tls": True
}
TLS_DOMAIN = "my-domain-fqdn"
MASK_HOST = "localhost"
MASK_PORT = 6443

**Comment by alexbers** [comment]
Hi!

Indeed, there was a bug. I fixed it in https://github.com/alexbers/mtprotoproxy/commit/8f48e9ef658c1ffd4024ce19b578d49d417d343e. Thank you for noticing
