### ISSUE TITLE
how off logger?

### ISSUE THREAD

**Issue by dark0ghost** [alexbers/mtprotoproxy#200]
how off logger? He eat many flash memory

**Comment by alexbers** [comment]
you cat insert:
```
STATS_PRINT_PERIOD = 10000000000
```

in the config.py

**Comment by ali-jk** [comment]
is there any way to clear the log?
or can I configure it somehow to show log for 24h?
I ran proxy for 10 days, with about 20 users, now it takes like 10 minutes to see the end

**Comment by alexbers** [comment]
the log size can be controlled here: https://github.com/alexbers/mtprotoproxy/blob/master/docker-compose.yml#L10
