### ISSUE TITLE
Problem with TAG

### ISSUE THREAD

**Issue by Zo0oX** [alexbers/mtprotoproxy#203]
when i'm run witout tag is ok whitout any problem, but when add tag its not work, not proxy not tag.
 whats the problem ?

**Comment by Zo0oX** [comment]
and this is error

`/home/ubuntu/mtprotoproxy# docker-compose logs
Attaching to mtprotoproxy_mtprotoproxy_1
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
`

**Comment by Zo0oX** [comment]
:/home/ubuntu/mtprotoproxy# docker-compose logs
Attaching to mtprotoproxy_mtprotoproxy_1
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent
mtprotoproxy_1  | Traceback (most recent call last):
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2353, in <module>
mtprotoproxy_1  |     main()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 2300, in main
mtprotoproxy_1  |     init_config()
mtprotoproxy_1  |   File "mtprotoproxy.py", line 106, in init_config
mtprotoproxy_1  |     conf_dict = runpy.run_module("config")
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 202, in run_module
mtprotoproxy_1  |     mod_name, mod_spec, code = _get_module_details(mod_name)
mtprotoproxy_1  |   File "/usr/local/lib/python3.8/runpy.py", line 154, in _get_module_details
mtprotoproxy_1  |     code = loader.get_code(mod_name)
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 916, in get_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
mtprotoproxy_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remov                                                                                               ed
mtprotoproxy_1  |   File "/home/tgproxy/config.py", line 27
mtprotoproxy_1  |     AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"
mtprotoproxy_1  |     ^
mtprotoproxy_1  | IndentationError: unexpected indent

**Comment by Zo0oX** [comment]
this is my config 

```
PORT = 443

# name -> secret (32 hex chars)
USERS = {
    "tg":  "00000000000000000000000000000001",
    # "tg2": "0123456789abcdef0123456789abcdef",
}

MODES = {
    # Classic mode, easy to detect
    "classic": False,

    # Makes the proxy harder to detect
    # Can be incompatible with very old clients
    "secure": False,

    # Makes the proxy even more hard to detect
    # Can be incompatible with old clients
    "tls": True
}

# The domain for TLS mode, bad clients are proxied there
# Use random existing domain, proxy checks it on start
# TLS_DOMAIN = "www.google.com"

# Tag for advertising, obtainable from @MTProxybot
 AD_TAG = "0511ea2913a8d7fb10d47e7dc686b3bc"

```

**Comment by seriyps** [comment]
Remove whitespace before `AD_TAG`

**Comment by Zo0oX** [comment]
> 
> 
> Remove whitespace before `AD_TAG`

thanks, proxy run, But Proxy sponsor is not worked, how can i fix this ?

**Comment by Zo0oX** [comment]
this is a secret in config file

 ```
  "tg":  "00000000000000000000000000000001",
    # "tg2": "0123456789abcdef0123456789abcdef",
}
```

but in export, this is secret

`ee000000000000000000000000000000017777772e676f6f676c652e636f6d`

and @MTProxybot do not accept this secret

how can i fix this problem for sponsor ?
