### ISSUE TITLE
A way for clearing the logs history

### ISSUE THREAD

**Issue by howdiw** [alexbers/mtprotoproxy#205]
Hello there and thanks for this configuration,
I use this script for personal usage with my friend, and everything is good.
A small problem is command ' docker-compose logs ', I have used this script for about 2 weeks and when I use this command, server shows me a long history from the proxy, and this big data cause the slow action of server. I want clear log history, is there any way or command?
Thank you again!

**Comment by erfantkerfan** [comment]
I did a pull request to limit the logging max file size and max file length also you can define your own file max size
but still hasn't been accepted

**Comment by alexbers** [comment]
Hello,

The instruction to clear the log is there: https://www.axllent.org/docs/view/clear-docker-log/

I've just commited the restriction of the logs size. It is up to 100MB now.
