### ISSUE TITLE
Get rid of hardcoded telegram IPs

### ISSUE THREAD

**Issue by seriyps** [alexbers/mtprotoproxy#21]
It would be nice to get rid of hardcoded telegram IPs

https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L75-L78

and use IPs from this URL https://core.telegram.org/getProxyConfig

statically or, better, download it periodically in background

**Comment by Nyoroon** [comment]
Also for ipv6 https://core.telegram.org/getProxyConfigV6

**Comment by alexbers** [comment]
Nice idea. I implemented it in https://github.com/alexbers/mtprotoproxy/commit/7071e31c2a6dd4eb6b35c5b744a21e4b8317784a
