### ISSUE TITLE
docker-compose error Temporary failure resolving 'deb.debian.org'

### ISSUE THREAD

**Issue by garywu520** [alexbers/mtprotoproxy#212]
[root@ecs]# docker-compose up -d
Building mtprotoproxy
Step 1/10 : FROM python:3.8-slim-buster
 ---> 56930ef6f6a2
Step 2/10 : RUN apt-get update && apt-get install -y libcap2-bin && rm -rf /var/lib/apt/lists/*
 ---> Running in 88b339eac8b2
Err:1 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'

Err:3 http://deb.debian.org/debian buster-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libcap2-bin
ERROR: Service 'mtprotoproxy' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y libcap2-bin && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by alexbers** [comment]
looks like temporary dns problems, should be fixed by now
