### ISSUE TITLE
how to deploy on heroku ?

### ISSUE THREAD

**Issue by todokku** [alexbers/mtprotoproxy#213]
Hi Alexander,
can you make procfile of dockerfile for easy deploy it on cloud containers like heroku ?

**Comment by lakudo** [comment]
I also tried to deploy on heroku, just add one line in procfile `worker: python3 mtprotoproxy.py`and made an empty  requirements.txt.  the app seems to be up, but it didn't work. when login in  the bash of app using`heroku run bash`, I got different proxy ip each time I ran `python3 mtprotoproxy.py`.

**Comment by black-cerberon** [comment]
Proxy is prohibited by Heroku's acceptable use policy.
https://www.heroku.com/policy/aup
