### ISSUE TITLE
Clients with time skew (possible replay-attackers)

### ISSUE THREAD

**Issue by komeylgivechi** [alexbers/mtprotoproxy#217]
hi 
mtproxy dont work until reset server!

log message is "Clients with time skew (possible replay-attackers)"

how to resolve this problom?

**Comment by alexbers** [comment]
Please check your server time

**Comment by komeylgivechi** [comment]
> Please check your server time
# timedatectl

 Local time: Mon 2020-04-20 12:43:39 EDT
  Universal time: Mon 2020-04-20 16:43:39 UTC
        RTC time: Mon 2020-04-20 16:37:30
       Time zone: America/New_York (EDT, -0400)
     NTP enabled: yes
NTP synchronized: no
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2020-03-08 01:59:59 EST
                  Sun 2020-03-08 03:00:00 EDT
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2020-11-01 01:59:59 EDT
                  Sun 2020-11-01 01:00:00 EST


what should I do now?

**Comment by alexbers** [comment]
If the time is bad, please, correct it

**Comment by komeylgivechi** [comment]
> If the time is bad, please, correct it

how should i recognize the **"bad"** time? what's the problem that you ask me to seek?

**plz tell me what should I do now to correct it?**

**Comment by alexbers** [comment]
Just compare the time on your server with the actual time. The difference should be < 1 min

**Comment by komeylgivechi** [comment]
> Just compare the time on your server with the actual time. The difference should be < 1 min

server location is germany

my location is iran

timezone server is america/ newyork


now what should i do?

**Comment by alexbers** [comment]
Try to put IGNORE_TIME_SKEW=True in the config.py and restart the proxy

**Comment by komeylgivechi** [comment]
[config.txt](https://github.com/alexbers/mtprotoproxy/files/4508000/config.txt)
 
is god config?

**Comment by alexbers** [comment]
```
PORT = 443

# name -> secret (32 hex chars)
USERS = {
    "komeyl":  "93f444b9f9df4cf8bdec8122d0e4a966",
}

MODES = {
	# Classic mode, easy to detect
    "classic": False,

    # Makes the proxy harder to detect
    # Can be incompatible with very old clients
    "secure": True,

    # Makes the proxy even more hard to detect
    # Can be incompatible with old clients
    "tls": True
}

# The domain for TLS mode, bad clients are proxied there
# Use random existing domain, proxy checks it on start
TLS_DOMAIN = "alexbers.com"

# Tag for advertising, obtainable from @MTProxybot
# AD_TAG = "3c09c680b76ee91a4c25ad51f742267d"
IGNORE_TIME_SKEW = True

```

**Comment by komeylgivechi** [comment]
> ```
> PORT = 443
> 
> # name -> secret (32 hex chars)
> USERS = {
>     "komeyl":  "93f444b9f9df4cf8bdec8122d0e4a966",
> }
> 
> MODES = {
> 	# Classic mode, easy to detect
>     "classic": False,
> 
>     # Makes the proxy harder to detect
>     # Can be incompatible with very old clients
>     "secure": True,
> 
>     # Makes the proxy even more hard to detect
>     # Can be incompatible with old clients
>     "tls": True
> }
> 
> # The domain for TLS mode, bad clients are proxied there
> # Use random existing domain, proxy checks it on start
> TLS_DOMAIN = "alexbers.com"
> 
> # Tag for advertising, obtainable from @MTProxybot
> # AD_TAG = "3c09c680b76ee91a4c25ad51f742267d"
> IGNORE_TIME_SKEW = True
> ```

Tnx workd
