### ISSUE TITLE
How to set the preferred network interface?

### ISSUE THREAD

**Issue by ali-jk** [alexbers/mtprotoproxy#229]
hi, I have 2 network interfaces on my server as eth0 & eth0:0 , how can I force your code to use eth0:0?
eth0 is banned in country but eth0:0 IP is working fine

**Comment by seriyps** [comment]
`LISTEN_ADDR_IPV4` in config.py

**Comment by ali-jk** [comment]
it should be like `LISTEN_ADDR_IPV4 = xxx.xxx.xxx.xxx`  correct?

**Comment by Kirya2k** [comment]
Yep
