### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by 9seconds** [alexbers/mtprotoproxy#24]
Hey! I would like to suggest you to use [timeouts](https://github.com/aio-libs/async-timeout) for read/write operations as [I do, for example, for mtg](https://github.com/9seconds/mtg/blob/master/proxy/timeoutrwc.go).

The rationale is quite simple: we might have some harmful clients (even attackers) who can write, let's say, 32 bytes for initial connection and send nothing after that. In that case, we would have an open socket for the infinite amount of time which can lead to the resource leak. Also, it would be trivial to destroy the proxy in such a way (just imagine, a small fleet of 20-30 machines which will do that for the proxy). Also, it helps to disconnect stale clients.

For mtg, I found out that 30 seconds is enough to have a great user experience. Nobody notices such timeouts on generic usage but I see these timeouts from time to time in the logs.

**Comment by 9seconds** [comment]
Keepalive is another thing. Let's imagine that client wrote only 32 bytes and does nothing after that. I mean, it just not sending any data further (evil client). The connection is alive, keepalive is working. The client just does not send any data further. In that case, the proxy will wait forever. A fleet of such clients is enough to exhaust all open file descriptors and crash proxy.

**Comment by CraftedCat** [comment]
Greate project, can you help me. How to check that proxy is MTProxy and alive on python3?
Интересный проект. Подскажите как проверить что прокси именно mtproto на python3? Просто есть канал, бот автоматом проверять сокет, но стали подсовывать другие сервисы ip:port

**Comment by alexbers** [comment]
To check that proxy is alive on python3 you can just try to connect on the proxy port with these commands:
import socket
s = socket.socket()
s.connect(("1.2.3.4", 3255))

where "1.2.3.4" is your ip to check

**Comment by 9seconds** [comment]
I see that discussion goes in absolutely another direction and it was actually implemented so I'll close this ticket if nobody minds.
