### ISSUE TITLE
Could not download media with Multi secret 

### ISSUE THREAD

**Issue by iPurya** [alexbers/mtprotoproxy#242]
Hi,
i have more than 100 secrets, and its necessary to be. in single secret and less than about 5 secrets there is no problem.
but when i'm increasing count of secrets, after 1 minute of connection to the proxy i could not download any media. just receiving text messages.
any ideas for fix this ?

**Comment by thisismzm** [comment]
According to [User management causing serious delays](https://github.com/alexbers/mtprotoproxy/issues/235#issuecomment-674967618), you can run several proxy servers on different ports with part of users on every proxy server.
