### ISSUE TITLE
"Error" when attempting to connect to proxy from Telegram X beta (Android)

### ISSUE THREAD

**Issue by K900** [alexbers/mtprotoproxy#25]
Running latest master and Telegram X 0.20.10.933-arm64-v8a, logcat shows nothing useful :(

**Comment by alexbers** [comment]
Could you try to retry with the latest version (stable or master), the 0d0a334 probable solve this. It seems the telegram updated its server software today

**Comment by K900** [comment]
No luck :(

**Comment by HirbodBehnam** [comment]
I tapped on those three dots on top right and then on "Show Error Details". This messages comes: `error (400: connection closed)`
I also tested [this repo](https://github.com/FreedomPrevails/JSMTProxy) and I get the same error.

**Comment by alexbers** [comment]
Thank you for patches, I merged almost all of them. Some of them were redesigned to get rid from global  QUICK_ACK_EXPECTED. Now the Telegram X should connect. Quick acknowledgements are also implemented in the latest master. For some reason the Telegram X beta for Android closes the connection when quick acks are used. I'll try to investigate why
