### ISSUE TITLE
Unable to connect to 2001:b28:f23f:f005::a 443- ipV4 and ipv6 problem

### ISSUE THREAD

**Issue by lion-goose** [alexbers/mtprotoproxy#251]
Suddenly a problem occurred today. At first I thought the port was blocked. After checking the log, it seems that the ipv6 API cannot be connected. 

![捕获](https://user-images.githubusercontent.com/59443350/121296639-9671a280-c923-11eb-989f-5842f1b44580.JPG)

My internet was ipV4 only and I would like to know how to solve it?
How can I modify it as I am not familiar with coding
Thanks.

**Comment by seriyps** [comment]
You can add

```
PREFER_IPV6 = False
```

to your `config.py`

**Comment by lion-goose** [comment]
> You can add
> 
> ```
> PREFER_IPV6 = False
> ```
> 
> to your `config.py`

thank you very much for your help!
This problem is solved!
