### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by thebrutish** [alexbers/mtprotoproxy#253]
Hi

TO_CLT_BUFSIZE = 262144
TO_TG_BUFSIZE = 262144

what is good number for 8 GB of RAM?
and how to make proxy use all CPU cores?

**Comment by erfantkerfan** [comment]
to answer to your second question this repo does not implement multi-core functionality so you have to manually run multiple instances

**Comment by alexbers** [comment]
The buffer sizes are good for 8 gb, but it depends on number of clients and on how far are they

**Comment by thebrutish** [comment]
> to answer to your second question this repo does not implement multi-core functionality so you have to manually run multiple instances

as I understand you mean for a 4 core CPU I should run this repo 4 times?

**Comment by erfantkerfan** [comment]
> > to answer to your second question this repo does not implement multi-core functionality so you have to manually run multiple instances
> 
> as I understand you mean for a 4 core CPU I should run this repo 4 times?

correct
but I dont know about serving that many users but you will find some help in older issues
like running some users in diffrent ports and running separate repos for hem
