### ISSUE TITLE
Question : replay attacks - Fake-TLS vs Secure randomized-packet-size

### ISSUE THREAD

**Issue by privatesupport** [alexbers/mtprotoproxy#271]
I have two question.

Does this project have Protection from replay attacks ???

I have a VPS and I run a website with https on this server. For preventing from DPI detection, Fake-TLS protocol (use my website domain for fake tls domain) is better or secure mode with randomize packet size (Specially in countries like Iran) ????

**Comment by hiddify** [comment]
Fake TLS is more secure
