### ISSUE TITLE
Maximum Secrets

### ISSUE THREAD

**Issue by HirbodBehnam** [alexbers/mtprotoproxy#28]
Is there a limit to maximum secrets? [Docker](https://hub.docker.com/r/telegrammessenger/proxy/) says it supports up to 16 secrets.

**Comment by HirbodBehnam** [comment]
NO NO NO! I mean the number of users(secrets) that I can use in one proxy. Not the string length. Docker says you can use 16 DIFFERENT secrets in one proxy.

**Comment by alexbers** [comment]
There is no limit in the program, however it is not recommended to use many users since it is slowing down the performance. But several hundreds should be ok.

**Comment by HirbodBehnam** [comment]
Ok thanks
