### ISSUE TITLE
.

### ISSUE THREAD

**Issue by alexdatur** [alexbers/mtprotoproxy#283]
.

**Comment by alexbers** [comment]
исправил возможную причину такого поведения: https://github.com/alexbers/mtprotoproxy/commit/88c8c57a44bfa0815c48bf759d8016380380279a

Пофиксило ли это проблему?

**Comment by ALEXSANPEDRO** [comment]
ТАк, на одном VPS затестил - вроде работает теперь быстро, и соединение и загрухка медиа. Еще сутки погоняю на этом и остальных серверах с повышением нагрузки пользователями и отпишусь ужк окончательно сюда.


Пока все выглядит так, словно проблема решилась

**Comment by ALEXSANPEDRO** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/63007698/220594239-590c9d87-8f8a-4042-8b82-0cd53e4ce9c5.png)
Поторопился, вот пример работы прокси. 

При переключении на другой впс, где стоит родная телеграмовская на C - таких ситуаций нет. Нагрузка на этом впс на прокю - 25 человек в час стабильно. Прокручивал ленту и вот сталкиваюсь что в ленте появляется много таких "вечных загрузок" которые тут же прогружаются при переключении на др проксю (не Python)

**Comment by aepot** [comment]
@alexbers 
Имел такую же проблему с долгим подключением к прокси, а также с непрогружающимися видео и картинками. Измучал весь фаервол, смотрел логи, дампы, включал/отключал сервисы (под капот смотрел, по колесам пинал), в общем весь сервер вверх дном перевернул, ничего не помогало. Мучался несколько месяцев, проксёй пользуюсь я и еще пара человек, то есть нагрузка детская. На VDS-ке в целом тоже все ресурсы свободны, ничего не нагружено.

Помогло изменение [MAX_CONNS_IN_POOL](https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L487) с 64 на 8 по мотивам #169, другие значения не пробовал. Уже неделю дня полёт нормальный, всё грузится, всё летает.

FreeBSD 13.1 x64, Python 3.9
