### ISSUE TITLE
cant register proxy via bot

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [alexbers/mtprotoproxy#285]
When i try to register mtproxy in off bot, and sell him a secret such as secret=ee20ea097c3*****845b6ded*****01fe177686f6****e6e6574 i have answer - Incorrect secret value. It must contain 32 hex characters like 
00112233445566778899aabbccddeeff.

If i use a secret which i generate for config.py, such a "20ea***c343c3184***ded2c***01**1" mtproxy bot takes it, but gives a link to my bot which ends secret=20ea***c343c3184***ded2c***01**1. BUT MY REAL SECRET WHICH IS GIVEN ME BY python proxy is ee20ea097c3*****845b6ded*****01fe177686f6****e6e6574. 

So what i must do for use statisticas and AD_TAG.

What i do wrong?

THX.

**Comment by alexbers** [comment]
you should put in AD_TAG = ".." the value from the official bot message that looks like:
"
Your proxy has been successfully registered. You can now pass this proxy tag to the software you are using: 3c09c680b76ee91a4c25ad51f742267d.
"
