### ISSUE TITLE
Windows Server Problem

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#29]
I run your mtproto successfully but cant connect to any client like Telegram Android or Telegram Desktop

![untitled](https://user-images.githubusercontent.com/40317198/41547409-5852ded4-7335-11e8-8cde-6f154875044f.jpg)

**Comment by ea1234567** [comment]
Do you have any guide or procedure?

Someone plz help me

**Comment by freekzy** [comment]
Did you set AD_TAG?

**Comment by HirbodBehnam** [comment]
Did you open that port on firewall? First time I also forgot to open my port on my firewall.

**Comment by ea1234567** [comment]
@HirbodBehnam Yes i opened that already but i have problem
Can you give me your Telegram id?

**Comment by HirbodBehnam** [comment]
I don't know Python AT ALL and I'm seriously noob in networking. But anyway "thyCrow"

**Comment by ea1234567** [comment]
no one tested this on windows server?

**Comment by ea1234567** [comment]
i checked that
its same as my clients time
@alexbers

**Comment by alexbers** [comment]
@bay3255
