### ISSUE TITLE
ERROR: Service 'mtprotoproxy' failed to build: The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -y python3 python3-uvloop python3-cryptography python3-socks libcap2-bin ca-certificates && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [alexbers/mtprotoproxy#297]
root@:~/mtprotoproxy# docker-compose up -d
Building mtprotoproxy
Step 1/8 : FROM ubuntu:22.10
 ---> 692eb4a905c0
Step 2/8 : RUN apt-get update && apt-get install --no-install-recommends -y python3 python3-uvloop python3-cryptography python3-socks libcap2-bin ca-certificates && rm -rf /var/lib/apt/lists/*
 ---> Running in 01321d354ba7
Ign:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu kinetic InRelease
Err:3 http://security.ubuntu.com/ubuntu kinetic-security Release
  404  Not Found [IP: 91.189.91.81 80]
Ign:4 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu kinetic Release
  404  Not Found [IP: 91.189.91.83 80]
Err:7 http://archive.ubuntu.com/ubuntu kinetic-updates Release
  404  Not Found [IP: 91.189.91.83 80]
Err:8 http://archive.ubuntu.com/ubuntu kinetic-backports Release
  404  Not Found [IP: 91.189.91.83 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu kinetic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-backports Release' does not have a Release file.
ERROR: Service 'mtprotoproxy' failed to build: The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -y python3 python3-uvloop python3-cryptography python3-socks libcap2-bin ca-certificates && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

При попытке развернуть проксю в докере на Ubuntu 20.04 - такая проблема. Как можно ее решить?

**Comment by alexbers** [comment]
похоже 22.10 перестал поддерживаться, я недавно обновил ветку master на 22.04. Или можно ещё 23.04 попробовать

**Comment by ALEXSANPEDRO** [comment]
Я вручную поправил на 20.04 и установка прошла успешно на ub 20 04 и прокся отлично работает!!!

**Comment by cjmaxik** [comment]
У кого будут проблемы в будущем, в файле Dockerfile меняете первую строчку на `FROM ubuntu:22.04`
