### ISSUE TITLE
Loop Problem (Windows)

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#30]
Can you fix windows specific loop please?
Common one only support 64 simultaneous connection
And windows specific one doesn't download photos

Thanks for this super script

**Comment by ea1234567** [comment]
@alexbers

**Comment by alexbers** [comment]
Could you please try to launch the proxy with the last unreleased version of python (3.7). It could be this bug: https://bugs.python.org/issue26819. Also I seen this https://bugs.python.org/issue33833 but it is not fixed yet

**Comment by ea1234567** [comment]
@alexbers  

OK , I will test that

**Comment by ea1234567** [comment]
@alexbers 

With 3.7 both of them have problem (windows specific and common one)

and proxy is unstable,many disconnection

**Comment by ea1234567** [comment]
@alexbers 

Whats your opinion?

**Comment by HirbodBehnam** [comment]
I think the problem is from your side. To just test, I installed Windows Sever 2016 on VMWare and set up this proxy's master branch on it with `pycryptonode` installed.(Python version 3.6.5) I installed OpenVPN Connect on server(to bypass censorship) and everything is working fine. I can upload, download and send messages. I haven't yet tried 64 simultaneous connections. 
For your uploading problem, have you installed `pycryptonode`?

**Comment by ea1234567** [comment]
@HirbodBehnam 
@alexbers 

Yes I already installed pycryptodome
My Python version is 3.6.5
I cant download images.but sending and recieving text messages is very fast
When i disable windows specific loop i can download images too , but common loop has limit (64 simultaneous connection)

Maybe windows 2008 has problem (you have windows 2016)

**Comment by HirbodBehnam** [comment]
Ok I tried that on Windows server 2008 RT. I couldn't connect to proxy at all unless I used loopback. I mean I downloaded Telegram Desktop on server and entered `localhost` as server ip. With that everything was fine.
Can you try to download telegram desktop on server and connect it through `localhost`?

**Comment by ea1234567** [comment]
@HirbodBehnam 
@alexbers 

I connected successfully with localhost and i don't have any problem with or without localhost
my problem is 64 simultaneous connection limit

You said that you cant connect with windows server 2008,what about server 2012? can you test it?

**Comment by HirbodBehnam** [comment]
@ea1234567 I don't have the ISO file.

**Comment by alexbers** [comment]
@ea1234567 could you try the latest version from master. I refactored the connection handling and how it should have less corner cases, which may fire in windows event loop implementation

**Comment by ea1234567** [comment]
@alexbers  

I dont have access to server now
I will test it 6 days later certainly (Wednesday 4 July)

**Comment by ea1234567** [comment]
@alexbers 

I tested problem is still remaining (windows server 2008)
I will test on windows server 2016 next week (7 july)

**Comment by alexbers** [comment]
Nice!
