### ISSUE TITLE
Cannot Connect to the server

### ISSUE THREAD

**Issue by amebrahimi** [alexbers/mtprotoproxy#32]
Hello, I am using this script for installing [mtproto](https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall) and when I try to connect to it the client starts trying to connect and it changes state between online and connecting and never connects. 
I have checked my firewall and opened the port but no success.

**Comment by HirbodBehnam** [comment]
I think this is a server issue. Also happens on [VirMach's affordable servers](https://virmach.com/best-cheapest-linux-vps/). We had some conversations [here](https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall/issues/1).

**Comment by ea1234567** [comment]
@amebrahimi 

1- You must set tag to your proxy
2- Your server and your client time must be the same

**Comment by amebrahimi** [comment]
@ea1234567 Will Test

**Comment by amebrahimi** [comment]
I have set the tag and changed my server time to my local time but no success

**Comment by ea1234567** [comment]
Windows or Linux?

**Comment by amebrahimi** [comment]
Linux Centos 7

**Comment by alexbers** [comment]
Could you retry with pycryptodome 3.6.1 (pip3.6 install --upgrade 'pycryptodome==3.6.1'). It seems that in 3.6.2 authors of pycryptodome "improved" the speed of aes three times, but the result became wrong

**Comment by HirbodBehnam** [comment]
@alexbers I can't test right now but you might be right because `pip show pycryptodome` returns version 3.6.1(On my VPS on Iomart)
I will test that as soon as I can.

**Comment by HirbodBehnam** [comment]
@amebrahimi Can you try downgrading to version 3.6.1? Use `pip3.6 install --upgrade 'pycryptodome==3.6.1'`

**Comment by amebrahimi** [comment]
Downgraded my `pycryptodome` to 3.6.1 and the problem was solved. thank you for your response

**Comment by HirbodBehnam** [comment]
Great! @alexbers can you put a warning somewhere in Readme? I will also update my own script.

**Comment by alexbers** [comment]
I posted a bug to pycryptodome: https://github.com/Legrandin/pycryptodome/issues/175

**Comment by alexbers** [comment]
The bug should be fixed in 3.6.3 https://pycryptodome.readthedocs.io/en/latest/src/changelog.html

**Comment by HirbodBehnam** [comment]
Nice can confirm that pycryptodome 3.6.3 is working fine.
