### ISSUE TITLE
Respond time

### ISSUE THREAD

**Issue by SimWhite** [alexbers/mtprotoproxy#34]
Hi. When I use official [mtproxy](https://github.com/TelegramMessenger/MTProxy) on the client it shows about 70ms ping. But when I use mtprotoproxy installed on the same server my client shows about 230ms ping. It’s about four times slower! Could someone explain why?

**Comment by Nihisil** [comment]
I have same numbers (90ms vs 210ms). But I don't have any delays with messages and images sending\receiving, so maybe these numbers not such important.

**Comment by SimWhite** [comment]
I also want to know how it calculated. Which metric it based on?

**Comment by alexbers** [comment]
Hi, the official proxy uses a connection pool of precreated TCP-connections, which speeds up the very first ping time. This implementation creates a TCP-connection to telegram when user connects to it which adds some latency. However, the scheme with connection creating allows to reduce memory consumption and slightly reduces a latency of further messages.
