### ISSUE TITLE
Don't work upload fotos and files in Telegram with FAST_MODE = True.

### ISSUE THREAD

**Issue by Kirya2k** [alexbers/mtprotoproxy#35]
Subj.
AD_TAG has disabled.

Additional info: Proxy working on IPV6 address, pycrypto&pycryptodome don't installed (yet), because proxy working on mips.

**Comment by alexbers** [comment]
Could you check the CPU load in the uploading time. If it is 100%, that means that its work, but slow. Are pycrypto and pycryptodome are available on mips?

**Comment by Kirya2k** [comment]
I understood. Thx !
Burden much too long that telegram will disconnected from proxy.
I am currently trying to compile  pycrypto or pycryptodome on Entware, and there are some problems with that.
But debian has bin-apt for mips and mipsel, so it's probably possible.

**Comment by Kirya2k** [comment]
Maintainer Entware of pycrypto compiled for mips.
Testing...
