### ISSUE TITLE
Can't install pycrypto or pycryptodome

### ISSUE THREAD

**Issue by aire1** [alexbers/mtprotoproxy#36]
I install pycrypto or pycryptodome on my machine, but the program doesn't see it and using AES.
Ubuntu 16.04

**Comment by HirbodBehnam** [comment]
In Ubuntu I think you just have to install `python3-crypto` package. 
Use `apt-get install python3-crypto`

**Comment by aire1** [comment]
oh, thanks:)

**Comment by aire1** [comment]
oh, thanks:)
