### ISSUE TITLE
Stats Problem

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#39]
MTProxy Bot never show me stats:

Sorry, we don't have stats for your proxy yet. Please come back later.

I changed port and secret key and tag but problem is remaining

I have another server and stats working fine
But in my new server i have stat problem

**Comment by alexbers** [comment]
Hello,

There is some lag between bot statistics update on the telegram side. Could you wait for some time e.g. 12 hours and see if the statistics was updated.

**Comment by ea1234567** [comment]
@alexbers 

But i waited more than 24h

**Comment by ea1234567** [comment]
@alexbers 

Problem solved after 30h

**Comment by alexbers** [comment]
nice!
