### ISSUE TITLE
[WinError 121] The semaphore timeout period has expired

### ISSUE THREAD

**Issue by Aloki** [alexbers/mtprotoproxy#40]
Such errors often appear in the output. However, this doesn't seem to affect the quality of the connection.
Windows 10 Build 17692, Python 3.7.0
```
Fatal read error on pipe transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x000002A9FF98A940>
transport: <_ProactorSocketTransport fd=748>
Traceback (most recent call last):
  File "C:\...\Python37\lib\asyncio\proactor_events.py", line 255, in _loop_reading
    data = fut.result()
  File "C:\...\Python37\lib\asyncio\windows_events.py", line 732, in _poll
    value = callback(transferred, key, ov)
  File "C:\...\Python37\lib\asyncio\windows_events.py", line 428, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
```

**Comment by ea1234567** [comment]
@Aloki

Thats loop bug in Python,I reported this to alexsbers already

With this error you cant load photos is telegram

**Comment by alexbers** [comment]
Hi! If everything works, I think those timeouts can be ignored. They are likely because some clients silently lose the connections. I added the code to ignore those errors: https://github.com/alexbers/mtprotoproxy/commit/6f8bfdb5685ecff55c6c7dba84fb6e69191864d6

**Comment by Aloki** [comment]
Yes, everything works. Nice, thanks!
