### ISSUE TITLE
Version 1.0.0 has less perfromance, than 0.9.5

### ISSUE THREAD

**Issue by devbreath** [alexbers/mtprotoproxy#41]
Hi,

After switching to version 1.0.0, I found, that clients may transfer data with less 250Kb/s. Version 0.9.5 executed on the same machine in separate docker provide 2,5Mb/s.
I changed size of buffer TO_CLT_BUFSIZE = 16384 via config.py and speed was improved to 510Kb/s (v1.0.0).
Both tests was done on the same physical machine, with different docker containers, the same secrets and the same clients(desktop and Android). If I switch to "secure" secret, I've also get less performance rate(v1.0.0).

Have you got any suggestions, why new version may be slower on the same secrets?

**Comment by ea1234567** [comment]
I have this problem too

**Comment by alexbers** [comment]
Hi,

There is a trade-off between memory consumption and performance. The more buffers you have, the more speed you are able to reach, but the more memory you need. The proxy can be launched on different hardware: on the machine with several hundreds GB of RAM, or on the small home router with hundreds MB of RAM. And the purpose of proxy can also be different: it can be for small company, or for large ones.

I am trying to specify the defaults to fit the requirements of most users. In the lattest version I increased its size back to 16384: https://github.com/alexbers/mtprotoproxy/commit/c2ad0de6651d2f9a9fc11bac0c3a3dcf650dffae. But if you need more speed, or have a lot of memory you can enlarge it even more until the speed will be satisfying.

Best,
Alexander Bersenev

**Comment by devbreath** [comment]
Thank you for explanation!
I am wondered, that version 1.0.0 slower than version 0.9.5, like 510Kb/s vs 2,5Mb/s (~5 times difference), even with the same buffer size. I can't find any reason for this.

**Comment by alexbers** [comment]
I think is because I forgot to set buffer sizes in some case: https://github.com/alexbers/mtprotoproxy/commit/675d5a6aba17f6571eb6909c70e3f69b58a03957#diff-e2b821dc5d96409f0102669d33aa8637R609. This caused the default OS limit was used, and it is a fairly big limit (about 400KBytes on my test OS).

**Comment by devbreath** [comment]
Just for information, a few seconds ago, I made new docker image from your master branch. Upload my config.py from version 0.9.5 and add follow strings:
TO_CLT_BUFSIZE = 16384
CLIENT_KEEPALIVE = 30*60
Speed of master branch ~600Kb/s
Speed of version 0.9.5 ~ 3Mb/s

**Comment by alexbers** [comment]
Could you, please try to remove this string from the do_direct_handshake function:
set_bufsizes(writer_tgt.get_extra_info("socket"), TO_CLT_BUFSIZE, TO_TG_BUFSIZE)

and rerun the test

**Comment by devbreath** [comment]
Thank you!

After this change, speed of master branch version increased to 2,6Mb/s - 3,06Mb/s

**Comment by ea1234567** [comment]
i increased buffer to 64000
and removed this string:

set_bufsizes(writer_tgt.get_extra_info("socket"), TO_CLT_BUFSIZE, TO_TG_BUFSIZE)

but still download speed is very low 

Version 0.9.5 was very fast

**Comment by alexbers** [comment]
could you, please, retry with these two string in config.py:
TO_CLT_BUFSIZE = 655360
TO_TG_BUFSIZE = 655360

**Comment by ea1234567** [comment]
Still very slow

250 KB/S

**Comment by alexbers** [comment]
also to make sure that this is due buffers, could you comment out all set_bufsizes calls (there should be two of them)

**Comment by ea1234567** [comment]
there was 3 set_bufsizes
i commented them all
proxy disconnected and many error,i cant connect

**Comment by ea1234567** [comment]
commented two of them and tested

still slow speed

**Comment by alexbers** [comment]
then, it is likely no due buffering changes. What is the CPU load during downloading?

**Comment by ea1234567** [comment]
cpu is normal during download and upload , cpu 3~7 percent

**Comment by alexbers** [comment]
the only variant left is the speed became slower due to internet provider of the server. Are you sure that the speed is still ok with v0.9.5?

**Comment by ea1234567** [comment]
yes im sure (0.9.5)

my server port is ok , download speed is above 20MB/S
and my download speed from telegram.org is 18MB/S

**Comment by ea1234567** [comment]
And in version 1.0.0 i get this error:

error updating middle proxy list
error updating middle proxy list for ipv6
error updating middle proxy list secret , using old

version 0.9.5 i dont get any error

**Comment by alexbers** [comment]
the logic of getting middle proxy list wasn't changed between 1.0.0 and 0.9.5. May be the packets from 1.0.0 are blocked by windows firewall?

**Comment by ea1234567** [comment]
Yes exactly

I turned off firewall and i dont get error any more

Picture download speed become very fast and improved a lot

Video download speed is still very very low 250KB/S

Do you have any idea for video?

And how can i turn firewall on witout proxy problem? I already opened my proxy port in firewall and i dont know which port telegram uses

**Comment by ea1234567** [comment]
@alexbers

**Comment by alexbers** [comment]
The video speed could be low because the video is downloaded from some far telegram datacenter. You can try to increase the buffer sizes even more or try to compose custom telegram servers list by modifying https://core.telegram.org/getProxyConfig, leaving only few fastest server from every group and assigning them to TG_MIDDLE_PROXIES_V4 variable and commenting out the  TG_MIDDLE_PROXIES_V4 = v4_proxies line. Also you can try to use "proxy_for 4" servers from "proxy_for -4" ones

**Comment by kmurachev** [comment]
> The video speed could be low because the video is downloaded from some far telegram datacenter. You can try to increase the buffer sizes even more or try to compose custom telegram servers list by modifying https://core.telegram.org/getProxyConfig, leaving only few fastest server from every group and assigning them to TG_MIDDLE_PROXIES_V4 variable and commenting out the TG_MIDDLE_PROXIES_V4 = v4_proxies line. Also you can try to use "proxy_for 4" servers from "proxy_for -4" ones

to @alexbers
скачанный getProxyConfig имеет вид

```
# force_probability 10 10
default 2;
proxy_for 1 149.154.175.50:8888;
proxy_for -1 149.154.175.50:8888;
proxy_for 2 149.154.161.144:8888;
proxy_for -2 149.154.161.144:8888;
proxy_for 3 149.154.175.100:8888;
proxy_for -3 149.154.175.100:8888;
proxy_for 4 91.108.4.130:8888;
proxy_for 4 91.108.4.149:8888;
proxy_for 4 91.108.4.171:8888;
proxy_for 4 91.108.4.156:8888;
proxy_for 4 91.108.4.219:8888;
proxy_for 4 91.108.4.137:8888;
proxy_for 4 91.108.4.131:8888;
proxy_for 4 91.108.4.194:8888;
proxy_for 4 91.108.4.185:8888;
proxy_for 4 91.108.4.195:8888;
proxy_for -4 149.154.165.109:8888;
proxy_for -4 149.154.166.120:8888;
proxy_for 5 91.108.56.194:8888;
proxy_for 5 91.108.56.130:8888;
proxy_for -5 91.108.56.194:8888;
proxy_for -5 91.108.56.130:8888;
```

[в текущем конфиге](https://github.com/alexbers/mtprotoproxy/blob/bc841cff482a72472f15a36f86ca01aa11cac58b/mtprotoproxy.py#L37) сейчас
```
    1: [("149.154.175.50", 8888)], -1: [("149.154.175.50", 8888)],
    2: [("149.154.161.144", 8888)], -2: [("149.154.161.144", 8888)],
    3: [("149.154.175.100", 8888)], -3: [("149.154.175.100", 8888)],
    4: [("91.108.4.136", 8888)], -4: [("149.154.165.109", 8888)],
    5: [("91.108.56.181", 8888)], -5: [("91.108.56.181", 8888)]
```

у меня самый лучший доступ к 91.108.4.137

правильно ли я понимаю, что нужно закомментировать
https://github.com/alexbers/mtprotoproxy/blob/bc841cff482a72472f15a36f86ca01aa11cac58b/mtprotoproxy.py#L2058
и записать следующим образом:
```
# This list will be updated in the runtime
TG_MIDDLE_PROXIES_V4 = {
    1: [("149.154.175.50", 8888)], -1: [("149.154.175.50", 8888)],
    2: [("149.154.161.144", 8888)], -2: [("149.154.161.144", 8888)],
    3: [("149.154.175.100", 8888)], -3: [("149.154.175.100", 8888)],
    4: [("91.108.4.137", 8888)], 4: [("91.108.4.137", 8888)],
    5: [("91.108.56.194", 8888)], -5: [("91.108.56.194", 8888)]
}
```
?

**Comment by alexbers** [comment]
можно попробовать, но только этот файл используется при запуске как fallback, т.е. при недоступности https://core.telegram.org/getProxyConfig. При доступности прокси сервер периодически ходит туда и обновляет список серверов
