### ISSUE TITLE
Error: Failed to determine your ip, advertising disabled

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#48]
I get this error:

Failed to determine your ip, advertising disabled

i entered my ip here:  ip_addrs = ["YOUR_IP"]

i can connect successfully to proxy but i don want get this error

whats problem? why my advertising disabled?

**Comment by devbreath** [comment]
I had this problem at sunday.

That problem was releated to the answer of resource https://v4.ifconfig.co/ip and https://v6.ifconfig.co/ip
So, I changed them to http://ipv4.myexternalip.com/raw and http://ipv6.myexternalip.com/raw in the script mtprotoproxy.py in lines 1066 and 1075

**Comment by ea1234567** [comment]
@devbreath  Thank You

This problem solved too

All of problems solved,Now this script is most complete and bugless script

**Comment by alexbers** [comment]
Hello, it seems the old ip obtaining service stop working.

So I switched it to another one: https://github.com/alexbers/mtprotoproxy/commit/c2278501bf25dd908db41aa136d7c27f5f881ec2

**Comment by jav4ds** [comment]
hi mr i set but i entered my ip here: ip_addrs = ["YOUR_IP"]
whats problem?

**Comment by alexbers** [comment]
could you please try the latest version,  the problem should be fixed there

**Comment by jav4ds** [comment]
The latest version is used
@alexbers

**Comment by alexbers** [comment]
Could you please check that the http://ipv4.myexternalip.com/raw address is available from the host. Also if you want to override the ip address logic, you can write my_ip_info["ipv4"] = "1.2.3.4" instead of init_ip_info() call, where 1.2.3.4 is your ip address
