### ISSUE TITLE
Unable to connect to some IPs

### ISSUE THREAD

**Issue by skipik** [alexbers/mtprotoproxy#49]
After making 'systemctl status MTProxy' I noticed these messages:

> Aug 03 22:43:28 ubuntu python3.7[984]: Unable to connect to 149.154.175.50 443
> Aug 03 22:43:28 ubuntu python3.7[984]: Unable to connect to 149.154.175.100 443
> Aug 03 22:43:36 ubuntu python3.7[984]: Unable to connect to 149.154.175.100 443
> Aug 03 22:43:36 ubuntu python3.7[984]: Unable to connect to 149.154.175.50 443
> Aug 03 22:43:44 ubuntu python3.7[984]: Unable to connect to 149.154.175.100 443
> Aug 03 22:43:44 ubuntu python3.7[984]: Unable to connect to 149.154.175.50 443
> Aug 03 22:43:52 ubuntu python3.7[984]: Unable to connect to 149.154.175.50 443
> Aug 03 22:43:52 ubuntu python3.7[984]: Unable to connect to 149.154.175.100 443
> Aug 03 22:44:00 ubuntu python3.7[984]: Unable to connect to 149.154.175.100 443
> Aug 03 22:44:00 ubuntu python3.7[984]: Unable to connect to 149.154.175.50 443

Is it some VPS-side problem or may be something wrong with those telegram servers?

**Comment by alexbers** [comment]
Could you try to connect to the server manually, for example with this command:
python3 -c 'import socket; s = socket.socket(); s.connect(("149.154.175.50", 443)); print("OK")'

If "OK" is not printed, then you likely have a network problems.

**Comment by skipik** [comment]
Yeah, I couldn't connect with that command, so its prob my VPS-side problem. Thank you for your help. :-)
