### ISSUE TITLE
SSL handshake failed     And     Fatal read error on pipe transport

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#51]
I can successfully connect to proxy but i get this error:

http://uupload.ir/files/123.png

Im using newest version

**Comment by alexbers** [comment]
Could you please try to install ca-certificates package or similar. Also these errors can occur if someone modifies your traffic between the proxy and telegram servers.

**Comment by ea1234567** [comment]
I installed Python 3.6.5 problem solved

Problem is with 3.7.0
