### ISSUE TITLE
limit users that can use proxy/secret

### ISSUE THREAD

**Issue by AliDjango** [alexbers/mtprotoproxy#52]
hello.i want to know is there way to limit the number of users that use a specific secret.for example only 32 people can use a specific secret.

if not,i don't know how to do it and i'm not familiar with mtproto proxy scheme.but i can change the code(and maybe PR if my code is usable).But i do need some help.
should it be limited by the number of IP's that are connected to a secret or do we have a ID for every single USER that connects to the secret?(and by secret i mean single secret not the whole proxy)

also can you hint me the lines that accept a connection,process them,where are open connection saved?

**Comment by alexbers** [comment]
hello, it is simple to patch the program to limit the number of users. For example to restrict the number of users with one secret with 32 you can replace the code:
```
    update_stats(user, curr_connects=1)
    await asyncio.wait([task_tg_to_clt, task_clt_to_tg], return_when=asyncio.FIRST_COMPLETED)
    update_stats(user, curr_connects=-1)
```

with this code:
```
    update_stats(user, curr_connects=1)
    if stats[user]["curr_connects"] <= 32:
        await asyncio.wait([task_tg_to_clt, task_clt_to_tg], return_when=asyncio.FIRST_COMPLETED)
    update_stats(user, curr_connects=-1)
```

**Comment by pouryare** [comment]
Hello

Is there any way to limit "curr_connects" just for specific users(secret), not for all the secrets?

**Comment by alexbers** [comment]
Hello,

yes, just by replacing 

     if stats[user]["curr_connects"] <= 32: 

with 

    if user == "any_username" and stats[user]["curr_connects"] <= 32:

**Comment by fa1996raz** [comment]
> hello, it is simple to patch the program to limit the number of users. For example to restrict the number of users with one secret with 32 you can replace the code:
> 
> ```
>     update_stats(user, curr_connects=1)
>     await asyncio.wait([task_tg_to_clt, task_clt_to_tg], return_when=asyncio.FIRST_COMPLETED)
>     update_stats(user, curr_connects=-1)
> ```
> 
> with this code:
> 
> ```
>     update_stats(user, curr_connects=1)
>     if stats[user]["curr_connects"] <= 32:
>         await asyncio.wait([task_tg_to_clt, task_clt_to_tg], return_when=asyncio.FIRST_COMPLETED)
>     update_stats(user, curr_connects=-1)
> ```

Hi can you please explain that is which file I should change the codes please?
I am using the windows version of this file that has been written with pyton that I dont know him, and there is nothing especial in config file except port and secrets and channel tag that I can change them.
And another question is there any way to make it work with radius?
I need radius for multi user limiting and setting expiration time for each secret, if there is any other way I would be very glad if you help me.
Thanks alot

**Comment by alexbers** [comment]
Hello, I've commited to master branch the ability to specify limits for users: https://github.com/alexbers/mtprotoproxy/commit/9da90d25d33e4a60d5793c4799dd940cbe21651e. 

Now you can put USER_CONN_LIMITS variable to config.py. Example:
```
USER_CONN_LIMITS = {
    "tg": 1
}
```

The radius is not supported.

**Comment by fa1996raz** [comment]
> Hello, I've commited to master branch the ability to specify limits for users: [9da90d2](https://github.com/alexbers/mtprotoproxy/commit/9da90d25d33e4a60d5793c4799dd940cbe21651e).
> 
> Now you can put USER_CONN_LIMITS variable to config.py. Example:
> 
> ```
> USER_CONN_LIMITS = {
>     "tg": 1
> }
> ```
> 
> The radius is not supported.

Hi and thanks alot for your quick response, As I said I am using it on windows and I think it has not been made by you, I had a question that if you have made an application for windows os too, you would give the download link please, or if it is not possible to make it, I am not too familar with Centos 7, you would help me to config it on an Centos server Step by Step if there is no problem, and another thing if you need the application that has been made for windows, I have the file and I think it has been developed for about a year and has not been updated, I can give the files.
Thanks again for your help
Hope to hear from you soon.

**Comment by HirbodBehnam** [comment]
@fa1996raz
Hi
You can use my script to install mtproto proxy on Centos 7 [link](https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall)

After installing you can edit `/opt/mtprotoproxy/config.py` to config your settings. (Adding limiter for example)

I will add the limiter option to script later.

Plus you can install mtproto on windows by simply downloading this repository and opening mtprotoproxy.py with python3 (You should download and install python from [here](https://www.python.org/downloads/release/python-373/) ) If python 3.7 didn't work try python 3.6

**Comment by fa1996raz** [comment]
> @fa1996raz
> Hi
> You can use my script to install mtproto proxy on Centos 7 [link](https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall)
> 
> After installing you can edit `/opt/mtprotoproxy/config.py` to config your settings. (Adding limiter for example)
> 
> I will add the limiter option to script later.
> 
> Plus you can install mtproto on windows by simply downloading this repository and opening mtprotoproxy.py with python3 (You should download and install python from [here](https://www.python.org/downloads/release/python-373/) ) If python 3.7 didn't work try python 3.6

Thanks man you are great
My only problem was executing these py projects, because I had never tried python before, I would try it now for both projects, 
Thanks again for your help🙏❤️

**Comment by pouryare** [comment]
@alexbers 
Would you please explain what's the difference between USER_CONN_LIMITS and USER_MAX_TCP_CONNS ?

**Comment by HirbodBehnam** [comment]
@pouryare 
From 6c5155ce0758f0183daa7af31580a19b346c64a5 `USER_CONN_LIMITS` has renamed to `USER_MAX_TCP_CONNS`.

**Comment by alexbers** [comment]
Yes, @HirbodBehnam  is right. I think `USER_MAX_TCP_CONNS` is a better name because the proxy limits the number of tcp-connections per users, not the users itself. One telegram client can establish about 5 simultaneous connection (e.g. for file downloading)

**Comment by HirbodBehnam** [comment]
I think limiting users could be possible with their IP addresses.
So with `print()` command I realized that from [here](https://github.com/alexbers/mtprotoproxy/blob/master/mtprotoproxy.py#L971) and `cl_ip` you can get the client's IP address. So if we store all IPs in a set (something like [std::set](https://en.cppreference.com/w/cpp/container/set) I'm not a Python programmer) we can count them. If they reach a specific number, close all other connections. Also remove IPs that timeout.
Sorry if my explanation was not clear.

**Comment by alexbers** [comment]
the limiting by ip address is much less precise than by ip addresses, since almost all providers use nat technology that hides many ip addresses behind one

**Comment by HirbodBehnam** [comment]
Yeah you are right
Home WiFis and organization WiFis will cause a lot of problems and inaccuracy later.

**Comment by hamid-sarani** [comment]
Hi @alexbers.

when i setting USER_MAX_TCP_CONNS, proxy works very slow? and cant download any thing
but when there is no USER_MAX_TCP_CONNS config, it's works fine!!!!

**Comment by alexbers** [comment]
The proxy can create several tcp connections for one user to download files fast. If you allow only few connections, like one or two, the proxy will be not able to make additional connections. You can just increase the connection limit, like if you want to have 10 user, then set 80 (multiply by 8)

**Comment by erfantkerfan** [comment]
Im wondering if there is a way to recognize each specific user and implement such restriction rather than aiming high with tcp connections or making the risk (nat) and limiting by IP. 🤔

**Comment by ali-jk** [comment]
> Hello, I've commited to master branch the ability to specify limits for users: [9da90d2](https://github.com/alexbers/mtprotoproxy/commit/9da90d25d33e4a60d5793c4799dd940cbe21651e).
> 
> Now you can put USER_CONN_LIMITS variable to config.py. Example:
> 
> ```
> USER_CONN_LIMITS = {
>     "tg": 1
> }
> ```
> 
> The radius is not supported.

hi I try this method but it's not working at all
```USER_CONN_LIMITS = {
	"karbar2": 2,
	"karbar1": 2,
	"karbar4": 1
}```
all of them are unlimited to connect.
did I do something wrong?
can you help me in some other way?

**Comment by alexbers** [comment]
Are you restarted the proxy after changing config?

Also one client can make about 8 connections, so the numbers are too low even for 1 client

**Comment by ali-jk** [comment]
I tried `USER_MAX_TCP_CONNS` and problem solved 
thank you

**Comment by ali4796** [comment]
hi alexbers 
I have several questions for you
Please comment on your Telegram ID

**Comment by bodacious-me** [comment]
Hi, can i use one tag that i get from the telegram bot for multiple secrets ? if yes how could i do that since the telegram bot generates a single tag for each secret
