### ISSUE TITLE
What the hell is USERS in config file?

### ISSUE THREAD

**Issue by elsieholmes** [alexbers/mtprotoproxy#53]
As far as I can see, it's some 32 hex char long value, but I have no blimmin' idea WHAT IT IS (and for?) and WHERE TO GET IT.

**Comment by alexbers** [comment]
It is a credential to connect to the proxy. You can use any 32 bytes long hex string you want. The clients should specify this string in the proxy settings.

**Comment by elsieholmes** [comment]
Thanks, got it.
