### ISSUE TITLE
Interface or IP binding

### ISSUE THREAD

**Issue by SimWhite** [alexbers/mtprotoproxy#54]
Hello. Is there any ways to bind proxy to the interface or ip address? I have a lot of IPs on the server and the proxy use all of them after start so I want to limit it and bind to the dedicated IP address.

**Comment by alexbers** [comment]
Hello, this feature has been just implemented: https://github.com/alexbers/mtprotoproxy/commit/298614b1f67f7fa548c4eb3682974cddb0addd1b

Now if you using the lattest version from master, please, add LISTEN_ADDR_IPV4 = "1.1.1.1"  to make it listen on 1.1.1.1.

**Comment by lgg** [comment]
@alexbers I think we need to add this to docs or README.md

**Comment by walkman99** [comment]
Hello!
It not worked. I set LISTEN_ADDR_IPV4 = "1.1.1.1" in config.py but proxy ignoring it and bind other address.

**Comment by SimWhite** [comment]
Everything works fine. It seems you incorrectly set the values ​​in the configuration file or use the old version.

**Comment by walkman99** [comment]
I'm using socks5 proxy and script bind address from proxy instead from interface. Is it correct in config.py to define address like this? 
LISTEN_ADDR_IPV4 = "1.1.1.1"

**Comment by walkman99** [comment]
Comment this string resolve problem:
`my_ip_info["ipv4"] = get_ip_from_url(IPV4_URL1) or get_ip_from_url(IPV4_URL2)`

**Comment by SimWhite** [comment]
Listen address can be different from the server address. `tg://proxy?server=185.220.xx.xx` — here you get your outside IP with NAT or something like that. But the listen address can be 192.168.1.1 i.e.
