### ISSUE TITLE
Number of workers?

### ISSUE THREAD

**Issue by nkvname** [alexbers/mtprotoproxy#58]
Hi! 

How to setup properly configuration, if I am using VPS with 4GB ram and 2CPU? 
Is there possibility to enable 2 number of workers?  

Currently ping is really high and it does not work so good with 1GB ram and 1CPU. 
Thanks.

**Comment by seriyps** [comment]
I think you can start 2 processes with the same config. Server uses REUSEPORT socket option, so, they will not conflict and OS will load-balance between workers
