### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MARL3N** [alexbers/mtprotoproxy#61]
Hi, i have error
mtproto proxy can't start
![914cc1ca08777195114a5c18c7506174](https://user-images.githubusercontent.com/43937273/46585951-3cd4be00-ca80-11e8-9d83-4642eb09d95f.png)

**Comment by alexbers** [comment]
Hi, could you please show the contents of /etc/systemd/system/mtprotoproxy.service file. Also do you have /usr/bin/python3.6 file in system?

**Comment by HirbodBehnam** [comment]
Looks like you used my script. This may be because of broken Python install. Try ro reinstall Python with `yum -y install python36`
