### ISSUE TITLE
Disable IPv6

### ISSUE THREAD

**Issue by lgg** [alexbers/mtprotoproxy#66]
I tried to set `PREFER_IPV6 = False` in `config.py` but mtprotoproxy is still running on ipv6 interface. 

Is it available to fully disable IPv6?

**Comment by lgg** [comment]
@alexbers do you welcome PR for this?

**Comment by alexbers** [comment]
Actually, you are the first one who've asked for this. If there will be more people with the same requirement I'll add an option for this.

**Comment by lgg** [comment]
@alexbers ok. Thank you for mtprotoproxy and support!
