### ISSUE TITLE
Add availability to use parent proxy (http/socks) and make variables in config.py for it, please.

### ISSUE THREAD

**Issue by zetcamp** [alexbers/mtprotoproxy#70]
Thx for project.

Can you add availability for using some parent proxy (not proxy for Telegram, but proxy for Internet access)? For example, there is some proxy server in a LAN which is used for Internet access. And there is no NAT/Direct connection here. That why I ask for adding some additional functionality.

I think that it will be some new variables in config.py.

**Comment by pasha-zzz** [comment]
I can do this and its very simple!
Install PySocks module and add `import socks` to mtprotoproxy.py
I set up cascade through local Tor. And without config options. Simple code change:
after line:
`def init_config():`
insert additional 2 lines:
```
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "localhost", 9050)
socket.socket = socks.socksocket
```
Replace localhost and 9050 with your SOCKS5 proxy address. Thats all!

**Comment by alexbers** [comment]
Also you can set this in the config.py:
MASK_HOST = "your_socks_proxy"
MASK_PORT = 1234

**Comment by pasha-zzz** [comment]
Then connects as SOCKS5 proxy. And connections from mtprotoproxy.py itself made directly. Not proxified.

**Comment by alexbers** [comment]
Done

**Comment by sae13** [comment]
> Also you can set this in the config.py:
> MASK_HOST = "your_socks_proxy"
> MASK_PORT = 1234

Failed to connect to MASK_HOST socks5://127.0.0.1: [Errno -2] Name or service not known

**Comment by sae13** [comment]
The MASK_HOST 127.0.0.1 is not TLS 1.3 host, this is not recommended
Error getting server time [Errno 110] Connect call failed ('10.10.34.35', 443)
Error updating middle proxy list: [Errno 110] Connect call failed ('10.10.34.35', 443)\





10.10.34.35' is block redirection url

**Comment by ieew** [comment]
I don't speak English, so the following answer is machine translated:

The correct `Socks5` configuration should be added in `config.py`
```python
SOCKS5_HOST = "127.0.0.1" # your socks proxy address
SOCKS5_PORT = 1081 # your socks proxy port
```

Here is my original text:

正确的 `Socks5` 配置应该是在 `config.py` 中添加
```python
SOCKS5_HOST = "127.0.0.1" # 你的 socks 代理地址
SOCKS5_PORT = 1081  # 你的 socks 代理端口
```
