### ISSUE TITLE
Channel Advertising disabled today

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#72]
Today my proxy disabled and i cant connect
but when i disable Channel Advertising i can connect to proxy again

i had no problem until today

we are waiting for fix . plz update proxy

tnx

**Comment by alexbers** [comment]
Hello, I checked the proxy on new host and it works. Your problem can happen it you have a time skew. Please, check you time. It should be precise (+/- 1 min of real time).
