### ISSUE TITLE
Error updating middle proxy list

### ISSUE THREAD

**Issue by ea1234567** [alexbers/mtprotoproxy#73]
In my new server when i enable AD_TAG i get this error:

Error updating middle proxy list 

i can connect to proxy but i cant see sponsored channel

i disabled firewall (i dont have antivirus) but problem not solved

i have good ping to telegram ip and server successfully determine my ip

**Comment by ea1234567** [comment]
Sponsored channel appeared but still i get this error:

Error updating middle proxy list

**Comment by alexbers** [comment]
Is https://core.telegram.org/getProxyConfig reachable from your host?

**Comment by ea1234567** [comment]
yes

**Comment by ea1234567** [comment]
im already using latest version

**Comment by alexbers** [comment]
Could you please send the Error updating middle proxy list in the latest version. Now it should contain the reason.

**Comment by ea1234567** [comment]
i tried again and i didn't get error anymore!!!!!!!!

why?!

i had error entire week

**Comment by alexbers** [comment]
Hm, I only extended the error reporting. Also, If the middle proxy site fails, I use the hardcoded list of middle proxies, so the proxy should work in any case.

**Comment by ea1234567** [comment]
tnx

closed
