### ISSUE TITLE
fake server in front of main server

### ISSUE THREAD

**Issue by erfantkerfan** [alexbers/mtprotoproxy#76]
is it possible to put a fake server in front that redirects all the traffic to main server.
I have clients that only can access this fake server IP internally but I want to bypass that and give them access to mtproto server.
If its possible please tell me how or point me to right direction.
thanks

**Comment by HirbodBehnam** [comment]
Hello
Yes it is possible with `iptables`. I've written a small guide in Persian for this. Read more here:
https://www.mediafire.com/file/r698z9czx9643c2/%25D8%25B6%25D8%25AF_%25D9%2581%25DB%258C%25D9%2584%25D8%25AA%25D8%25B1_%25DA%25A9%25D8%25B1%25D8%25AF%25D9%2586_MTProto_Proxy.pdf/file

**Comment by erfantkerfan** [comment]
the link is broken

**Comment by HirbodBehnam** [comment]
Retry with VPN. (Outside of Iran)
