### ISSUE TITLE
install in blocked country

### ISSUE THREAD

**Issue by old-joker** [alexbers/mtprotoproxy#78]
Hi 
is there any new way to bypass in blocked area ?
ISP's in iran detect proxy very soon and block it 
1. change random padding character "dd" to "gs" or something else , is it possible ? 
2. change packet size or customize packet's header 
3. change server ip or domain every day ? or have method to change auto ? 
4. send mtproxy traffic over vpn like openvpn or IKEV2 or Tunnel

**Comment by VahidN** [comment]
@old-joker 
They count the number open TCP connections to your server. That's how they detect what's the purpose of your server.

**Comment by old-joker** [comment]
1. i'm not sure but think "dd" characters are fixed can change it to random character for example i said "gs" or "za"  ... . do you think is it help to bypass filtering ?
2. do you now how to implant round-robin DNS ? or can we use HAproxy for load balance clients ? 
3. how can we setup cluster for mtproxy servers ? any idea ?

**Comment by HirbodBehnam** [comment]
Hello
1. If just changing, 99% not it will not help.
2. 80%, No. The blocking bot *may* try to re-ping the server again and block the IP.
3. Not sure and never thought of. If you just want to split the connection with CPU threads, yes you can re-run this script again but the [Official Proxy](https://github.com/TelegramMessenger/MTProxy) provides a better performance. In Official Proxy you can set number of workers.
