### ISSUE TITLE
ipv4.myexternalip.com is not working

### ISSUE THREAD

**Issue by beeyev** [alexbers/mtprotoproxy#79]
https://github.com/alexbers/mtprotoproxy/blob/b0cb48f684a9b6a710f7b6ec7668c56b5dbcfbca/mtprotoproxy.py#L1111

Service http://ipv4.myexternalip.com/raw does not work anymore.
I suggest to replace it with http://v4.ident.me/ and http://v6.ident.me/

**Comment by alexbers** [comment]
The bug has been fixed in https://github.com/alexbers/mtprotoproxy/commit/73592c4f72632c5261dbba2d15b1f85c6d00088e. Thanks for reporting!
