### ISSUE TITLE
no logs

### ISSUE THREAD

**Issue by iShift** [alexbers/mtprotoproxy#8]
i don't get any logs with 
`docker-compose logs`

if i run 
without docker - i get logs

**Comment by alexbers** [comment]
Hi, it seems there was a typo in a starting print parameter.

Should be fixed by: https://github.com/alexbers/mtprotoproxy/commit/00f87d955bbd83b0ad92811b5af25c86a4701e8f

The bug should be fixed. Could you recheck, please

**Comment by iShift** [comment]
hmm, on Mac i get logs, on Ubuntu - don't 
```
user@server:~/mtprotoproxy/mtprotoproxy$ docker-compose logs
Attaching to mtprotoproxy_mtprotoproxy_1
```

**Comment by alexbers** [comment]
did you launch docker-compose up --build ?

**Comment by iShift** [comment]
my fault, after rebuild it works
