### ISSUE TITLE
Program keep saying that install Cryptography package!

### ISSUE THREAD

**Issue by Mahyar24** [alexbers/mtprotoproxy#81]
i have installed cryptography by using pip, but i still getting this warning to install it!
`To make the program a *lot* faster, please install cryptography module: pip install cryptography
`
i'm commenting this because the ping and latency is okay but using an external VPN for telegram is very faster for downloading the files rather than this approach! [is there anything that i can do to make downloading files a little bit faster?!]

**Comment by HirbodBehnam** [comment]
Have you tried `pip3 install cryptography` or `pip3.6 install cryptography `?

**Comment by Mahyar24** [comment]
That's the point! 
First i uninstalled cryptography package which was installed by pip; then i installed it with pip3 and then execute the program with python3 (not python3.7!). It's now working very fast and smoothly!
