### ISSUE TITLE
problem in commit

### ISSUE THREAD

**Issue by erfantkerfan** [alexbers/mtprotoproxy#82]
in this commit on stable branch:
https://github.com/alexbers/mtprotoproxy/commit/73592c4f72632c5261dbba2d15b1f85c6d00088e
this line:
IPV4_URL1 = "http://v4.ident.me/)"
has a an extra ")" in it
the correction would be:
IPV4_URL1 = "http://v4.ident.me/"

**Comment by alexbers** [comment]
Good catch! Fixed in https://github.com/alexbers/mtprotoproxy/commit/830d55fe7759871c7b0722a78522670b616c4001. Thank you!
