### ISSUE TITLE
ufw setup

### ISSUE THREAD

**Issue by erfantkerfan** [alexbers/mtprotoproxy#86]
Hi
if I deny all ports via ufw BOTH In and Out, which port should I open for it to work correctly.
say I ran my proxy on port 2020
sudo ufw allow 2020
sudo ufw allow out 2020
![Image of derver](http://uupload.ir/files/tp4k_untitled.png)
the above config disconects users
help me please

**Comment by erfantkerfan** [comment]
I figured it out
I should open port 8888 as well
is it possible to change this code?

`TG_MIDDLE_PROXIES_V4 = {
    1: [("149.154.175.50", 8888)], -1: [("149.154.175.50", 8888)],
    2: [("149.154.162.38", 80)], -2: [("149.154.162.38", 80)],
    3: [("149.154.175.100", 8888)], -3: [("149.154.175.100", 8888)],
    4: [("91.108.4.136", 8888)], -4: [("91.108.4.136", 8888)],
    5: [("91.108.56.181", 8888)], -5: [("91.108.56.181", 8888)]
}

TG_MIDDLE_PROXIES_V6 = {
    1: [("2001:b28:f23d:f001::d", 8888)], -1: [("2001:b28:f23d:f001::d", 8888)],
    2: [("2001:67c:04e8:f002::d", 80)], -2: [("2001:67c:04e8:f002::d", 80)],
    3: [("2001:b28:f23d:f003::d", 8888)], -3: [("2001:b28:f23d:f003::d", 8888)],
    4: [("2001:67c:04e8:f004::d", 8888)], -4: [("2001:67c:04e8:f004::d", 8888)],
    5: [("2001:b28:f23f:f005::d", 8888)], -5: [("2001:67c:04e8:f004::d", 8888)]
}`

because I'm being attacked at this port and I get almost a gigabit traffic as I open this port.
any help?

**Comment by seriyps** [comment]
I guess you can open 8888 only for outgoing connections

**Comment by erfantkerfan** [comment]
When I open 8888 outgoing port I get attacked by cycling IPs about a BigaByte/minute

**Comment by seriyps** [comment]
why do you think it's an attack? Do you have an examples of those "cycling IPs"?

**Comment by erfantkerfan** [comment]
because its a continues data stream and does not stop and it changes its destination IP from time to time.
No there isn't any of those IPs in the attackers IP
![Annotation 2019-04-30 232316](https://user-images.githubusercontent.com/37825504/56986128-384c3000-6b9f-11e9-9c22-3c0cb12b5960.jpg)
![Annotation 2019-04-30 232511](https://user-images.githubusercontent.com/37825504/56986129-384c3000-6b9f-11e9-9ad5-2733c7600bff.jpg)
there is 2 sets of those IPs in the screenshot

**Comment by seriyps** [comment]
well, ok, I don't know what might it be
