### ISSUE TITLE
freezing fingerprint in ubuntu 16

### ISSUE THREAD

**Issue by m8603164** [alexbers/mtprotoproxy#92]
Unfortunately, I encounter this error in DigitalOcean server:

_active fingerprinting detectedfrom x.x.x.x, freezing it._

Please advise how to fix it?

[image1](https://pasteboard.co/Ifpd02k.jpg)
[image2](https://pasteboard.co/Ifpdvzt.jpg)

**Comment by HirbodBehnam** [comment]
Hello
Can you retry with python 3.6 instead of 3.5?

**Comment by alexbers** [comment]
the active fingerprinting detected occurs when the proxy detect the active fingerprinting. Without this detection, the proxy would be blocked.

The update recommendation is a good one. But in python 3.5 after these messages the proxy should continue working.
