### ISSUE TITLE
Multi users and AD_TAG

### ISSUE THREAD

**Issue by thisismzm** [alexbers/mtprotoproxy#94]
Hello.
I have a question about AD_TAG.
I'm running this script with PORT 443 but I'm using different ports when I share my proxy to others and I'm doing this with local port forwarding. #85
When I want to get a tag from `MTProxybot` it wants from me to enter an IP and a port and then it will generate a tag for me and I will set it to AD_TAG in my config file.
Will this tag work for other ports too? for example, if I get the tag for port 443 does this tag works for port 80 too? Will I get the right stats from this robot?
Thanks.

**Comment by HirbodBehnam** [comment]
I think yes

**Comment by thisismzm** [comment]
> I think yes. You can use that tag.

Yes, I tested it but will `MTProxybot` include the stats of other ports in its stats?

**Comment by karimi12** [comment]
yes,
AD_TAG  work with different port even  ip 
i tested it

**Comment by ea1234567** [comment]
> > I think yes. You can use that tag.
> 
> Yes, I tested it but will `MTProxybot` include the stats of other ports in its stats?

Yes
